bvcms/bvcms

- CmsData/Email/EmailReplacements.cs
- CmsData/Email/Emailer.cs
- CmsData/Finance/ManagedGiving.cs
- CmsWeb/Areas/OnlineReg/Controllers/Confirm.cs
- CmsWeb/Areas/OnlineReg/Models/ManageGivingModel.cs
Take a look at this to see if it makes sense or could be improved. I am using two DataContexts and the inner one is disposed after each recipient. The outer database context will contain any changes to the EmailQueueTo object.
> Speed up SendPeopleEmail for large List

- CmsWeb/Areas/Org/Views/OrgGroups/Index.cshtml
Opening this for @steven-bvcms
> Fix for team scores not updating

- CmsWeb/Areas/Manage/Views/Display/Index.cshtml
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/SpecialRegModel.cs
Update to Special Content to show entries with a empty name or title
> Update to Javascript Registration to accept bool

- CmsWeb/Areas/People/Controllers/ContactController.cs
So the page won't stay in edit mode when Javascript requests a page reload
> Added code to remove the "edit=true" query string

- UtilityExtensions/Emailer.cs
Fix for the issue @karenworrell noticed in PR #88.  Since that PR is closed, I'm creating a new one with this fix.  I'm on Linux at the moment and haven't tested this, but it should work.
> Only display CC message when CCing

- CmsWeb/Areas/Public/Controllers/CheckInAPIController.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIController.cs
Update drop date for both the mobile app and check-in app to "Now" instead of "Today"
> Fixed link for "Give Without Account" on the mobile app

- CmsWeb/Areas/Public/Controllers/CheckInAPIController.cs
Fixed new person always being a child
> Limited name search to 200 results

- CmsData/Organization/OrganizationMember.cs
- CmsWeb/Areas/Org/Controllers/OrgGroupsController.cs
- CmsWeb/Areas/Org/Models/Org/SettingsAttendanceModel.cs
- CmsWeb/Areas/Org/Models/OrgGroupsModel.cs
- CmsWeb/Areas/Org/Views/Org/Settings/Attendance.cshtml
- CmsWeb/Areas/Org/Views/Org/Settings/AttendanceEdit.cshtml
- CmsWeb/Areas/Org/Views/OrgGroups/Form.cshtml
- CmsWeb/Areas/Public/Controllers/MobileAPIController.cs
- CmsWeb/Areas/Reports/Models/Attendance/RollsheetModel.cs
- CmsWeb/Content/touchpoint/js/org/org-groups.js
- SqlScripts/BuildDb/Creating_dbo_OrgMemMemTags.sql
- SqlScripts/BuildDb/Creating_dbo_Organizations.sql
- SqlScripts/BuildDb/Creating_dbo_RollList.sql
Continues discussion from [this pull request](https://github.com/bvcms/bvcms/pull/109)
Had to create new pull request due to git issues on my end.
Test server http://dev.nwbbc.org:44401
Username: admin
Password: touchpoint.1
> Mobile App: Roll List filtered for Sub-Group leaders

- CmsWeb/Areas/Public/Controllers/CheckInAPIController.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIController.cs
Added ability to add family picture to both MobileAPI and CheckInAPI
> Fix for null object on Entry Point

- CmsWeb/Areas/Manage/Models/AccountModel.cs
Branch can be deleted after merge
> Fix for checking roles

- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInPrintLabel.cs
Branch can be deleted after merge
> Fixed an issue with "No security label required" on printing

- CmsWeb/Areas/Public/Controllers/MobileAPIController.cs
- CmsWeb/Areas/Public/Models/MobileAPI/BaseMessage.cs
- CmsWeb/Areas/Public/Models/MobileAPI/PostObjects/MobilePostCreate.cs
Branch can be deleted after merge
> Routines for creating an account from the mobile app

- CmsWeb/Areas/Public/Controllers/MobileAPIController.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobileOrganization.cs
Added fix for "Any Day" schedule item
Ad-hoc routine will not look at future meetings
> Updates to mobile attendance org list

- CmsWeb/Areas/Org/Models/Org/OrganizationModel.cs
- CmsWeb/Areas/Public/Models/SGMapModel.cs
The visits role check fix is minor.
The SGF address fix introduces a new setting called `SGF-ExtraValueHost`. If it is set, then it allows for the small group host address to be set in an extra value instead.
> Minor permission fix and SGF address customization

- CmsWeb/Areas/Public/Models/SGMapModel.cs
- CmsWeb/Areas/Public/Models/SmallGroupFinderModel.cs
- CmsWeb/Areas/Public/Models/SmallGroupSearchResult.cs
- CmsWeb/Areas/Public/Views/SmallGroupFinder/Index.cshtml
- CmsWeb/CmsWeb.csproj
When the small group finder starts, it doesn't show results so the code
returns all orgs; however, this caused a problem when no results were
found from search results - it didn't know if it was the initial search
or not.
> Handle issue with no SGF results coming back

- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInPrintLabel.cs
Added check for worker to use correct number of labels for workers
> Updated mobile check-in printing routine defaults

- CmsWeb/Areas/Main/Controllers/EmailController.cs
- CmsWeb/Areas/Main/Views/Email/Index.cshtml
- CmsWeb/Areas/Public/Models/OrgContentInfo.cs
- CmsWeb/CmsWeb.csproj
Kayan tested this for us. In addition, here are the test cases I used:
- users
- admin
- org leader
- MyData user
- org content checks
- click email all
- click email for individuals
> Fix for emailing individuals versus orgs from the custom member only page

- CmsData/Extensions/Person.cs
- CmsWeb/Areas/People/Views/Person/DisplayTemplates/InlineCodeEditCampus.cshtml
- CmsWeb/Areas/People/Views/Person/Personal/Header.cshtml
- CmsWeb/Areas/People/Views/Person/Resources/Tab.cshtml
- CmsWeb/CmsWeb.csproj
- CmsWeb/Web.config
Please take a look at the changes we've made to the Resources and Edit Campus functionalities.
For EditCampus:
===========
Please create the following Setting(s):    EnforceEditCampusRole = (true)
Please add the following role(s):  EditCampus
** Expected results:
- User should be able to edit his/her own (or family member) CAMPUS (Congregation)
- User should be able to edit others' CAMPUS -- only if he/she has the EditCampus role.
For Resources:
=========
First panel of each category will open automatically.
No changes to the database nor settings.
> Edit campus and Resources changes

- CmsWeb/Areas/People/Views/Person/Resources/Tab.cshtml
Reconstructed code block using Pull Request #149:
> Code Reconstruction

- CmsData/API/PythonModel/Email.cs
Update to the Python Email class to allow python to create emails that will be sent at a scheduled time.  For example, Faith Community Church wants to use this to send an automated follow up email following registrations.  The OnRegister script in the registration will create the email, scheduled at a later time so that it doesn't appear automated.
> Scheduled emails

- CmsWeb/Areas/Public/Controllers/CheckInAPIController.cs
- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInAddEditPerson.cs
- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInFamily.cs
- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInFamilyMember.cs
- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInMessage.cs
- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInPerson.cs
- CmsWeb/CmsWeb.csproj
Added Father and Mother name to Add/Edit Person
Misc other updates
> Added Alt Name to all Check-In functionality

- CmsWeb/Areas/Public/Controllers/MobileAPIController.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIListController.cs
- CmsWeb/Areas/Public/Models/CheckInAPI/CheckInPrintLabel.cs
- CmsWeb/Areas/Public/Models/MobileAPI/BaseMessage.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobileFamilyMember.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobileHomeAction.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobilePerson.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobilePersonAddress.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobilePersonExtended.cs
- CmsWeb/Areas/Public/Models/MobileAPI/PostObjects/MobilePostAddPerson.cs
- CmsWeb/Areas/Public/Models/MobileAPI/PostObjects/MobilePostEditField.cs
- CmsWeb/CmsWeb.csproj
> Added features for My Profile in mobile app

- CmsWeb/Areas/Dialog/Views/OrgMemberDialog/Tabs/MemberData.cshtml
- CmsWeb/Areas/Dialog/Views/OrgPrevMemberDialog/Tabs/MemberData.cshtml
Two views were changed to fix the issue.
> BUG: User without Edit should not be able to access the Transaction History date and edit it.

- CmsWeb/CmsWeb.csproj
- CmsWeb/Models/ExtraValue/NewExtraValueModel.cs
This fixes the issue with standardizing extra values that was reported.
> Null check around extra value codes (#117)

- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Flow2/PersonFind.cshtml
Finishing the Trello ticket. There should be only one file that has been changed.
> NoPhoneEmailonFind Extra value - Name suffix Field

- CmsData/Organization/Organization.cs
- CmsWeb/Areas/OnlineReg/Controllers/OnePageGiving.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/OnePageGivingModel.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Helper.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/OtherInfo.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/OnePageGiving/Index.cshtml
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/OnePageGiving/Login.cshtml
- CmsWeb/Areas/Org/Views/Org/Dialogs.cshtml
- CmsWeb/CmsWeb.csproj
- CmsWeb/Code/ViewExtensions.cs
- CmsWeb/Content/css/onlinereg2.css
This PR includes one page giving flow enhancements. The login page for one page giving now more closely matches the login page for MyData and staff users. The login now redirects back to one page giving and autofills user details based on their profile. Finally, multi-fund support is added to one page giving.
Includes the following Sifter tickets:
* https://clearfunction.sifterapp.com/issues/919
* https://clearfunction.sifterapp.com/issues/918
* https://clearfunction.sifterapp.com/issues/917
cc @brianlankford1
> One Page Giving Flow Enhancements

- CmsWeb/Areas/Search/Views/SearchAdd/SearchPerson.cshtml
> Code fix to search page not showing in other places.

- README.md
As someone who is new to Windows development and coming from a background in mobile/iOS development, I found the initial dev environment setup to be harder than it needed to be. The general steps were there but small yet essential steps seemed to be missing, at least when I tried setting it up.
Through talking to David, it looks like the majority of the language was updated already. I've just gone ahead and fixed some typos and fixed the code snippets to be more clear. I also renamed the file to be all-caps to follow normal conventions.
> Update and rename ReadMe.md to README.md

- CmsWeb/Areas/People/Models/Task/TaskModel.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAuthentication.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileMessage.cs
Updated Task routines for new mobile API
> Updated Authentication routine for new mobile API

- CmsData/API/PythonModel/Handlebars.cs
- CmsData/Classes/OnlineRegSummaryText/Details2.xml
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Enroll.cs
Amount display changes in registration email.
> Keerthi display amounts

- CmsWeb/Areas/People/Views/Person/Giving/Contributions.cshtml
- CmsWeb/Areas/Public/Controllers/ExternalServicesController.cs
1. RCCC more error details.
2. Check images hidden for non finance users.
> Check images visible by role, RCCC SSO Error Details

- CmsWeb/Areas/Manage/Models/UpdateFieldsLookups.cs
- CmsWeb/Areas/Manage/Models/UpdateFieldsModel.cs
Add "do not call" as an option for the field to update and handle setting the DoNotCallFlag if the user chooses that field to update.
> Add "do not call" as field in batch update operations

- CmsData/API/APIContributionSearchModel.cs
- CmsData/CmsData.csproj
- CmsData/Extensions/ContributionFundExtensions.cs
- CmsData/Generated/ContributionFund.cs
- CmsData/Migrations/20180720_StoredProcedure_CHAIDonationsReport2.sql
- CmsData/Migrations/20180720_StoredProcedure_GetDepositDateTotalsUsingAuthorizedFunds.sql
- CmsData/Migrations/20180720_Table_ContributionFunds.sql
- CmsWeb/Areas/Finance/Controllers/FinanceReportsController.cs
- CmsWeb/Areas/Finance/Controllers/FundController.cs
- CmsWeb/Areas/Finance/Models/DepositTotalsModel.cs
- CmsWeb/Areas/Finance/Models/TotalsByFundAgeRangeModel.cs
- CmsWeb/Areas/Finance/Models/TotalsByFundModel.cs
- CmsWeb/Areas/Finance/Models/TotalsByFundRange.cs
- CmsWeb/Areas/Finance/Views/Fund/Edit.cshtml
- CmsWeb/Code/CodeInfo.cs
- CmsWeb/Code/CodeValueList.cs
- CmsWeb/Code/CodeValueModel.cs
Code changes required for assigning a role to a fund and modifying the reports to honor that role when selecting source data
> Austin allowed fund dynamic role

- CmsWeb/Areas/Finance/Models/BundleModel.cs
> Change order for dropdown to be based off of fund name. This only affects these dropdowns.

- CmsWeb/Areas/Finance/Controllers/PostBundleController.cs
- CmsWeb/Areas/Finance/Models/BundleModel.cs
- CmsWeb/Areas/Finance/Models/PostBundleModel.cs
I didn't include this list in the original branch as I overlooked it when reading the card.
> another list of funds to make alphabetical

- CmsData/Classes/Twilio/TwilioHelper.cs
- CmsData/CmsData.csproj
- CmsData/Email/Emailer.cs
- CmsData/Generated/Organization.cs
- CmsData/Migrations/20180719_send-attendance-link.sql
- CmsWeb/Areas/Org/Models/Org/SettingsAttendanceModel.cs
- CmsWeb/Areas/Org/Views/Org/Settings/AttendanceEdit.cshtml
- DbmlBuilder/DbmlBuilder/CodeGeneration/Templates/CS_ContextTemplate.aspx
- DbmlBuilder/DbmlBuilder/CodeGeneration/Templates/CS_EntityTemplate.aspx
- DbmlBuilder/DbmlBuilder/CodeGeneration/Templates/CS_TableFunctionTemplate.aspx
- DbmlBuilder/DbmlBuilder/Program.cs
- SqlScripts/BuildDb/Creating_dbo_Organizations.sql
These are changes to support the group leader attendance message feature
> Send group leader attendance messages

- CmsData/DbUtil/Context.cs
This is used primarily for database conversions
> Fix the creation of a new fund when there are no funds in the database

- CmsWeb/Areas/Finance/Models/BatchImport/FbcFayettevilleImporter.cs
Client changing banks, modified contribution importer to match their new file format.
> Austin modify importer fbcfayetteville

- CmsWeb/Views/Home/Support2.cshtml
Change the text for critical issues when contacting support per request
> Modify wording for critical issues

- CmsData/Extensions/Contact.cs
- CmsData/Extensions/Family.cs
- CmsData/Extensions/Person.cs
- CmsData/Meetings/Meeting.cs
- CmsData/Organization/Organization.cs
- CmsData/Organization/OrganizationMember.cs
These functions would trim to find the existing values but did not trim to insert them. 😦
> Extra values inserting when field exists due to white space

- CmsWeb/Areas/OnlineReg/Controllers/ManageGiving.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/ManageGiving/Setup.cshtml
- CmsWeb/Content/touchpoint/js/onlinereg/OnlineRegPayment2.js
- CmsWeb/Web.config
Modification to have a better way to update credit card information.
There are three fields required when updating credit card information, "credit card number", "expiration date" and "CVV".
UI has been changed to guide the user to update all those required fields or cancel the information update process.
> Josearmando update cc expiration date

- CmsWeb/Areas/People/Models/Person/Giving/ContributionsModel.cs
https://trello.com/c/wLzsDVwL/5112-error-an-iqueryable-that-returns-a-self-referencing-constant-expression-is-not-supported
> Fixed linq error in ContributionModel causing exception.

- CmsData/Extensions/User.cs
https://trello.com/c/KTjiyHGG/5117-add-financedataentry-role-as-option-when-editing-user-roles
> Add the role to the finance group on useredit page

- CmsWeb/Areas/Finance/Models/ContributionStatements.cs
https://trello.com/c/B37SgHbv/5141-2-envelope-number-on-statement-admin-rccc-rccc-25103
> add envelope number to statements if flag is set

- CmsData/Classes/RoleChecker/RoleChecker.cs
- CmsWeb/Areas/Org/Models/Org/OrgPeopleModel.cs
- CmsWeb/Areas/Org/Views/Org/People/GroupButtons.cshtml
https://trello.com/c/cPRPfxAL/5138-add-customaccessrole-setting-for-hidepreviousorgmembers
> Add logic to hide the previous tab for org leaders 

- CmsWeb/Areas/People/Models/Person/PersonModel.cs
See card: 1 Error accessing individual accounts: Susana Gough @ redeemer [25698] CAUSED BY DESIGNATING LEADER TYPES FOR RESOURCE 181
> Add check before using the dictionary to validate the key exists

- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAuthentication.cs
> Updated mobile authentication routines to include OrgLeadersOnly

- CmsData/CmsData.csproj
- CmsData/Migrations/20181004_update_NonTaxDed_include_both_contributions.sql
- CmsWeb/Areas/Finance/Models/TotalsByFundModel.cs
1. Modify how NonTaxDed param value is get, handled and passed to GetTotalContributionRange table scalar function in SQL.
2. Modify GetTotalContributionRange function to execute ContributionSearch passing to it the proper value for both TaxDed and NonTaxDed contributions.
> Financial reporting discrepancy

- CmsData/CmsData.csproj
- CmsData/Migrations/20181011_update_spouseId_function.sql
Database SpouseId function updated in order to return the PeopleId that is married to another people according to the Married flag (which is set in MaritalState lookup table) instead MaritalId = 20
> Database SpouseId function update

- CmsData/CmsData.csproj
- CmsData/Generated/Context.cs
- CmsData/Generated/PushPayLog.cs
- CmsData/Migrations/20181015_add_pushpay_schema.sql
https://trello.com/c/BIfjMYSf/5146-pushpay-track-import-progress-schema-logic
> add pushpay schema

- CmsWeb/Views/Shared/SearchBox.cshtml
https://trello.com/c/BQUa3E4n/5189-while-doing-a-quick-search-the-1st-found-match-should-be-opened-when-the-user-presses-enter
> pressing enter will take you to the first item if no item has been selected from the search results

- CmsWeb/CMSWeb.csproj
- CmsWeb/Controllers/ScriptController.cs
- CmsWeb/Models/ScriptModel.cs
- CmsWeb/packages.config
The issue had to do with loosing P1 parameter value when attempting to execute query.
> Fix to get BundleReport2 up and running.

- CmsWeb/Areas/Manage/Models/UploadPeopleModel.cs
For InsertPeople (with excel file) process: Include method to getMaritalId by description instead of hardcoded values.
> Modifications for InsertPeople (upload by Excel file)

- CmsData/Migrations/20181013_update_contributions2_func.sql
correct bug in master preventing local development due to database creation error
> fix typo in migration preventing local build

- CmsWeb/Areas/Manage/Models/VolunteerRequestModel.cs
https://trello.com/c/8xlyJCGp/5204-2-confirmation-for-volunteers-mary-catherine-mckee-centralchurchnyc-26046-clean-up-p-html-code-in-email
> adjust html tag in email so message is rendered correctly

- CmsWeb/Areas/Manage/Models/VolunteerRequestModel.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/VolSubModel.cs
https://trello.com/c/KQK921oP/5209-correct-spelling-of-volunteer-sub-confirmation-email-subject
> Correct spelling error in vol request and vol sub email subject lines

- CmsWeb/Areas/Finance/Models/BatchImport/AbundantLifeImporter.cs
- CmsWeb/Areas/Finance/Models/BatchImport/BatchImportContributions.cs
https://trello.com/c/4UzfSOIb/5200-2-kindrid-text-to-give-import-paul-cumberland-abundantlife-25985
> update abundant life importer to accept new file format

- CmsData/CmsData.csproj
- CmsData/Extensions/User.cs
- CmsData/Migrations/20181031_add_viewvolunteerapplication_role.sql
- CmsWeb/Areas/People/Views/Person/Ministry/Volunteer.cshtml
- CmsWeb/Areas/People/Views/Volunteering/Display.cshtml
- CmsWeb/Areas/People/Views/Volunteering/Index.cshtml
- CmsWeb/Content/touchpoint/js/people/person.js
- CmsWeb/Content/touchpoint/js/people/volunteering.js
For Manage Volunteers page, (1) add confirmation button when deleting a document, and (2) create a new role to view documents but not be able to change checkboxes, etc.
> Manage Volunteers Changes

- CmsWeb/Areas/OnlineReg/Controllers/OnePageGiving.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/HelperMethods.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/OnePageGiving/NotActive.cshtml
- CmsWeb/CMSWeb.csproj
This disables One Page Giving when Org is inactive. Registered Closed still only disable Online Registration.
> Disable One Page Giving when Organization is inactive

- CmsData/API/PythonModel/Contributions.cs
- CmsData/CmsData.csproj
- CmsData/Migrations/20181111_alter_Contributions2SearchIds_func.sql
- CmsData/Migrations/20181111_create_TagContributionsFromIds_proc.sql
@brondavies it would be very helpful if you could run the migration script 20181111_alter_Contributions2SearchIds_func.sql today on MP database. This does not depend on any of the other code in this PR. This will allow me to wrap up the first phase of the project with MP right away. No one else is using this function at this point so it should innocuous.  Thank you.
> Giving dashboard additional contribution search capabilities

- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
Mike comment in Request Id: 26149
Recurring Giving is now disabled for inactive orgs.
> Disable Recurring Giving for Inactives Orgs

- CmsWeb/Areas/People/Models/Task/TaskModel.cs
- CmsWeb/Areas/Search/Models/TaskSearch/TaskSearchModel.cs
This fixes issue when creating or saving tasks/contacts - https://trello.com/c/DnURdjh8
> Fix Task update.

- CmsWeb/CMSWeb.csproj
- CmsWeb/Controllers/Api/CustomController.cs
- CmsWeb/Controllers/Api/PostController.cs
- CmsWeb/Global.asax.cs
- CmsWeb/Web.config
- CmsWeb/packages.config
- UnitTests/app.config
https://trello.com/c/pxAWKmos/5274-bug-error-when-using-api-support-tp-re-error-messages
> Register dependencies for web api controllers

- CmsData/API/PythonModel/DynamicData.cs
- CmsData/API/PythonModel/Misc.cs
- CmsData/API/QueryFunctions/Query.cs
- CmsWeb/ConnectionStrings.config
The second dashboard, Household Giving report, depends on these changes.
I will document in the bvcmsdocs repo as soon as I finish this project with MP
> PythonModel.DynamicData Improvements for GivingDashboard project

- CmsData/CmsData.csproj
- CmsData/packages.config
- UtilityExtensions/Config/AppConfig.cs
- UtilityExtensions/Extensions/StringExtensions.cs
- UtilityExtensions/Extensions/TypeConversions.cs
- UtilityExtensions/UtilityExtensions.csproj
Most of these changes are just being added to support the new customer database conversion system.
> Enhancements for new conversion routines

- CmsWeb/Areas/People/Models/Contact/ContactModel.cs
- CmsWeb/CMSWeb.csproj
Avoiding duplicate selection in Role List for contacts.
> Avoiding duplicate selection in Role List for contacts.

- CmsData/CmsData.csproj
- CmsWeb/Areas/Manage/Controllers/BatchMoveAndDelete.cs
- CmsWeb/Areas/Manage/Views/Batch/OtherDeveloperActions.cshtml
- CmsWeb/CMSWeb.csproj
- CmsWeb/packages.config
https://trello.com/c/PBrbryak/5304-bug-error-when-trying-to-use-various-batch-actions-under-the-other-developer-actions-screen
> fix url for batch move and delete

- CmsWeb/Areas/People/Controllers/Person/PersonalController.cs
- CmsWeb/Areas/People/Models/Person/BasicPersonInfo.cs
critical support issue, edit of people not working due to model state validation errors
> Update validation for email address to enforce 150 characters instead of 20

- CmsWeb/Areas/People/Models/AddressInfo.cs
https://trello.com/c/gKGUu1mI/5317-bug-from-date-not-saving-in-address
> include from date when getting and saving addresses

- CmsWeb/Views/Shared/Menu/Organization.cshtml
This menu option is hidden unless the setting "EnableCheckinCoordinator" is set to "true"
> Daniel hide checkin coordinator

- CmsWeb/Areas/People/Controllers/Person/GivingController.cs
- CmsWeb/Areas/People/Models/Person/Giving/ContributionsModel.cs
- CmsWeb/Areas/People/Models/Person/Giving/StatementInfo.cs
- CmsWeb/Areas/People/Views/Person/Giving/StatementsWithFund.cshtml
- CmsWeb/CMSWeb.csproj
https://trello.com/c/wMdhFxCM/5243-create-an-option-to-generate-a-fund-based-contribution-statement-for-my-data-users
> Modify statements view to aggregate by fund

- CmsWeb/Areas/People/Models/Person/Giving/ContributionsModel.cs
https://trello.com/c/wMdhFxCM/5243-create-an-option-to-generate-a-fund-based-contribution-statement-for-my-data-users
> Add logic using setting to group by fund or group by year for statements

- CmsData/API/APIContributionSearchModel.cs
https://trello.com/c/BoFR21WU/5343-2-contributions-search-ryanne-caldwell-2pc-32216
> search expects null result for no fund set

- CmsData/API/APIContribution.cs
- CmsData/CmsData.csproj
- CmsData/Generated/Functions/Donor.cs
- CmsData/Migrations/20190118_alter_donors_function_for_spouse_legal_name.sql
https://trello.com/c/jvi0O8td/5320-2-names-on-contribution-statements-not-consistent-admin-rccc-rccc-32061
> Add new column for use with the notitlesonstatements setting

- CmsWeb/Areas/Finance/Controllers/ContributionsController.cs
- CmsWeb/Areas/Finance/Models/ContributionSearchModel.cs
- CmsWeb/Areas/People/Views/Person/Giving/StatementsWithFund.cshtml
https://trello.com/c/wMdhFxCM/5243-create-an-option-to-generate-a-fund-based-contribution-statement-for-my-data-users
> Fix urls to generate custom statements or limit to passed fund set from individual statement when using fund statements

- CmsWeb/Areas/People/Views/Volunteering/DialogSubmit.cshtml
- CmsWeb/Content/touchpoint/js/people/volunteering.js
js updated to disable submit button.
> Preventing PMM form from submitting more than once.

- CmsData/API/QueryFunctions/Query.cs
- CmsData/DbUtil/Context.cs
- CmsData/DbUtil/Session.cs
- CmsWeb/Areas/Finance/Controllers/ContributionsController.cs
- CmsWeb/Areas/Finance/Views/Contributions/Index.cshtml
- CmsWeb/Models/ScriptModel.cs
This will facilitate reconciliation to Python Reports
> Expose FilterByActiveTag to Contribution Search

- CmsData/CmsData.csproj
- CmsData/Email/ReplacementCodes/DoReplaceCode.cs
- CmsData/Email/ReplacementCodes/EmailReplacements.cs
- CmsData/Email/ReplacementCodes/Links/UnlayerLink.cs
- CmsWeb/Areas/Main/Views/Email/Compose.cshtml
- CmsWeb/Content/touchpoint/js/email/compose.js
https://trello.com/c/lDv3IEko/5349-new-special-links-dialog-for-email-builder-feature
> Td email special links

- CmsWeb/Areas/Manage/Controllers/UploadAddressesController.cs
https://trello.com/c/LXyyWjyX/5393-bug-kayan-at-redeemer-is-getting-an-error-when-trying-to-use-the-developer-tool-upload-addresses
> pass correct context from background task

- CmsWeb/Areas/Manage/Models/UploadAddressesModel.cs
https://trello.com/c/LXyyWjyX/5393-bug-kayan-at-redeemer-is-getting-an-error-when-trying-to-use-the-developer-tool-upload-addresses
> Modify the model as well as the controller to use the proper context

- CmsWeb/Areas/Setup/Controllers/MetroZipController.cs
> Fix Resident Code Bug when user creates a range of zip codes.

- CmsWeb/Areas/Manage/Models/UpdateFieldsModel.cs
https://trello.com/b/eMreQii8/development
> Add to dropdown on UI and add logic to set from newvalue

- CmsWeb/Controllers/ScriptController.cs
Background worker needs proper context sent to python model
> Pass data context to python model in background worker

- CmsWeb/Areas/Search/Controllers/QueryController.cs
- CmsWeb/Areas/Search/Models/Query/Model/QueryModel.cs
https://trello.com/c/TwxXSZmn/5350-2-issue-with-tag-all-in-search-builder-tags-all-people-records-becky-gossard-salemalliance-32046
> Austin tag and untag modifications

- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- CmsWeb/Areas/Public/Models/MobileAPI/BaseMessage.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobileRollList.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAuthentication.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileGivingContribution.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileGivingStatement.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileMeetingCategory.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileMessage.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileUserPrivileges.cs
- CmsWeb/CMSWeb.csproj
Added extended Giving Statement starter
Updated MobileAuthentication routines to use new database object
> Added Meeting Category APIs

- CmsWeb/Areas/OnlineReg/Controllers/SaveAndContinue.cs
When Model.RegistrantComplete = true redirect to completeregistration action.
> Redirect to complete registration action automatically

- CmsWeb/Areas/OnlineReg/Controllers/Payment.cs
Creating actions for coupon calls (POST)
> Creating POST actions for Confirm and ConfirmDuePaid.

- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
- CmsWeb/Areas/OnlineReg/Controllers/Routing.cs
Build participant selector right after login.
> Fix Mission Trip Support Bug

- CmsWeb/Areas/People/Controllers/Person/GivingController.cs
- CmsWeb/Areas/People/Views/Person/Giving/Contributions.cshtml
Updated the route to one time giving button click to check for campus mapping route in settings and use that route over the default redirect.
> Redeemer Giving Btn Update

- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Giving/Goer.cshtml
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Giving/Guest.cshtml
https://trello.com/c/c3bYtzwE/5060-add-goer-funding-page-for-rush-creek
> update completed progress bar width, add copy url share option to guest view

- CmsData/DbUtil/Context.cs
- CmsWeb/Areas/People/Controllers/Person/PersonController.cs
https://trello.com/c/TwxXSZmn/5350-2-issue-with-tag-all-in-search-builder-tags-all-people-records-becky-gossard-salemalliance-32046 fixes the other 2 spots for tagging
> Fix tagging to use created tagname and set in util2

- CmsWeb/Areas/Manage/Models/UploadPeopleModel.cs
https://trello.com/c/GgQ7K9lC/5443-error-with-txt-fields-during-lite-conversion-process
> remove the id- text from being added to ExtraText

- CmsData/Extensions/Person.cs
https://trello.com/c/eR3lAOKC/5394-bug-error-when-trying-to-merge-record-at-cross-church
> handle existing giving in merge target

- CmsWeb/Areas/Main/Views/Email/Compose.cshtml
- CmsWeb/Areas/Manage/Controllers/DuplicatesController.cs
- CmsWeb/Content/touchpoint/js/email/compose.js
https://trello.com/c/VzyLAwlD/5483-2-redeemers-email-builder-not-opening-unlayer-editor-kayan-wong-redeemer-35457
* fix js lint errors
* fix closing tag on email composer which prevented unlayer modal from working
* fix context create method call to include connection string (had to do this to fix a build error after merging in stable - not sure what happened here)
> Td unlayer fixes

- CmsWeb/Areas/Finance/Models/BatchImport/BatchImportContributions.cs
https://trello.com/c/GMjL0IHH/5427-create-upload-script-re-touchpoint-software-re-2-online-giving-not-using-an-authorized-merchant-barbara-waldrop-cottonwood-32814?menu=filter&filter=member:austinlippert3
> Add new header row for triggering subsplash import

- CmsData/Email/ReplacementCodes/Links/UnlayerLink.cs
https://trello.com/c/1CUwGpL4/5496-1-email-builder-special-link-errors-drew-hall-redeemer-35540
> fix showfamily flag error

- UtilityExtensions/Extensions/TypeConversions.cs
This method is used when importing oledb source files.
> Adding new methods to Util for type safety

- CmsWeb/Areas/OnlineReg/Models/OnlineReg/FamilyMembers.cs
Moved error logic up the stack a bit and specified the model error key to be specific for the member selected to register.
> Redeemer Community Group Fix

- CmsData/Email/ReplacementCodes/Links/IsSpecialLink.cs
https://trello.com/c/1CUwGpL4/5496-1-email-builder-special-link-errors-drew-hall-redeemer-35540
> make sure tracklinks is compatible with new special link format

- CmsWeb/Content/touchpoint/js/email/compose.js
https://trello.com/c/cnieCFVS/5219-enhancement-have-a-confirm-prompt-in-place-to-prevent-sending-an-email-accidentally-that-will-come-up-after-clicking-send-the-fi
> add confirmation prompt before sending email

- CmsWeb/Areas/Main/Models/Other/MassEmailer.cs
- CmsWeb/Areas/Main/Views/Email/Compose.cshtml
- CmsWeb/Content/touchpoint/js/email/compose.js
https://trello.com/c/cnieCFVS/5219-enhancement-have-a-confirm-prompt-in-place-to-prevent-sending-an-email-accidentally-that-will-come-up-after-clicking-send-the-fi
> enable prompt based on EmailPromptBeforeSend setting

- CmsData/Organization/OrgFilter.cs
https://trello.com/c/1SFu0okC/5546-bug-blank-space-prefixed-in-name-search-under-org-people-tab
> Td org name filter fix

- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/ValidateModelQuestions.cs
Supporters can make a general donation even if they don't support a specific participant.
> Add validations for mission trips.

- CmsWeb/Content/touchpoint/js/email/compose.js
https://trello.com/c/KIlZlCkN/5569-2-bug-email-double-sending-nathan-barley-bellevue-36000
> Daniel prevent send double email

- CmsWeb/Areas/Main/Controllers/EmailController.cs
https://trello.com/c/ipRkGe5s/5518-2-email-composer-adding-specific-recipients-not-working-kayan-wong-redeemer-35655
> fix for sending emails to additional recipients

- CmsWeb/Areas/Reports/Controllers/ReportsController.cs
- CmsWeb/Areas/Reports/Models/Attendance/MeetingAttendanceModel.cs
- CmsWeb/Areas/Reports/Views/Reports/MeetingAttendance.cshtml
- CmsWeb/Code/CodeValueModel.cs
trying this again..https://trello.com/c/RgVCK0H9/5479-meeting-types-report-for-fielder
> td meeting types report update

- CmsWeb/Areas/Reports/Models/Attendance/MeetingAttendanceModel.cs
include organizations in non primary divisions where division filter is active
>  td meeting types report update 2

- CmsWeb/Areas/OnlineReg/Models/OnlineReg/Constructor.cs
- CmsWeb/Areas/Org/Views/Org/Dialogs.cshtml
https://trello.com/c/ecU3lxR6/5604-1-user-selects-org-registration-set-up-nick-wilbur-ingleside-36214
> fix reg testing link for logged in users with allow anonymous org setting

- CmsWeb/Areas/Main/Views/Email/Index.cshtml
- CmsWeb/Content/touchpoint/js/email/Email.js
https://trello.com/c/KIlZlCkN/5569-2-bug-email-double-sending-nathan-barley-bellevue-36000
> Daniel fix email confirmation prompt bug

- CmsData/CmsData.csproj
- CmsData/Migrations/20190527_add_preconfigured_acceptiva_details.sql
https://trello.com/c/qV0UdIfh/5295-custom-dev-build-integration-to-acceptiva-for-payment-processing-for-st-ann-parish
> Add preconfigured Acceptiva gateway details

- CmsWeb/Areas/OnlineReg/Models/OnlineReg/Constructor.cs
https://trello.com/c/ecU3lxR6/5604-1-user-selects-org-registration-set-up-nick-wilbur-ingleside-36214
> handle disallow anonymous registration attempt when logged in

- CmsWeb/Areas/Reports/Controllers/ReportsController.cs
- CmsWeb/Areas/Reports/Models/Attendance/MeetingAttendanceModel.cs
- CmsWeb/Areas/Reports/Views/Reports/MeetingAttendance.cshtml
https://trello.com/c/yVDUogG3/5634-disable-auto-run-for-attendance-by-meeting-type-report
> don't run the report without parameters

- CmsWeb/Areas/People/Views/Person/Resources/Tab.cshtml
https://trello.com/c/1n51tRMO/5452-resource-type-name-does-not-allow-apostrophe-2-resource-type-issue-jason-skinner-whcchome-34189
> allow special characters in resource types

- CmsWeb/Areas/OnlineReg/Controllers/ManageVolunteers.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/ManageVolunteer/PickSlots.cshtml
- CmsWeb/Content/touchpoint/js/volunteer/ManageVolunteer.js
https://trello.com/c/4gLhv5Hn/5492-redeemer-getting-error-when-they-click-on-any-getsub-link-on-vol-calendar-after-first-one-is-successful
> make getsub link behavior more consistent

- CmsData/Classes/OnlineRegSummaryText/Details2.xml
- CmsData/Organization/OrganizationMember.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/EnrollAndConfirm.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Enroll.cs
Related to https://trello.com/c/AoKgjVaN/5629-1-parkside-church-member-in-ohio-received-a-receipt-from-ingleside-laurie-admin-ingleside-36473
This change validates if the email body contains the correct registrants.
> Validate email body registrants

- CmsData/Finance/TransNationalGateway.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/PaymentForm.cs
https://trello.com/c/E24Ie2bB/5497-bug-user-payments-not-shown-as-approved-in-tp-but-processed-by-transnational-2-registration-issue-wayne-brown-ebcjackson-34350
The system was trying to insert a new row in PeopleExtra table using People Id = 0. This change fixes that.
Also, I've implemented a new message to show in case transaction will be approved but registration failed.
> Fixing ACH Transnational People Extra issue

- CmsWeb/Areas/People/Controllers/Person/GivingController.cs
- CmsWeb/Areas/People/Views/Person/Giving/Contributions.cshtml
- CmsWeb/Areas/Public/Controllers/MobileAPIController.cs
- CmsWeb/CMSWeb.csproj
- CmsWeb/Controllers/Api/AuthenticateController.cs
https://trello.com/c/Zmq0r3x4/5663-external-recurring-and-one-time-giving-links
> External giving links and OTL token validation

- CmsData/CmsData.csproj
- CmsData/packages.config
- CmsWeb/CMSWeb.csproj
- CmsWeb/libman.json
- CmsWeb/packages.config
- RepairOrg/App.config
going back one version seems to resolve our issues with this package
https://trello.com/c/eWlRZK7x/5649-bug-500-error-family-directory-kimberly-ohara-stanwichchurch-36592
> revert xceed.words.net package version

- CmsWeb/Areas/Manage/Views/Transactions/List.cshtml
https://trello.com/c/rW2IbaMR/5657-1-complaint-about-change-in-transactions-martha-witcher-bellevue-36624
> Fix transaction popover issue

- CmsWeb/Areas/Dialog/Views/GetCheckImage/GetCheckImage.cshtml
- CmsWeb/Content/touchpoint/js/search/search-add.js
https://trello.com/c/M5H0hdeN/5662-2-check-display-locks-system-up-jeannie-lewis-mountpisgah-36639
> make check display dismissable by keyboard or mouse

- CmsData/QueryBuilder/Expressions/Admin.cs
- CmsData/QueryBuilder/Expressions/AttendanceHistory.cs
- CmsData/QueryBuilder/FieldMap.csv
- CmsData/QueryBuilder/GetExpression.cs
- CmsData/QueryBuilder/QueryType.cs
Not sure about the order by clause.
I am not sure if it is:
1) birthdate only
2) birthdate, name and People ID Number
> Revision to new search builder condition GetEldestFamilyMember (revised #550)

- CmsData/Finance/TransNationalGateway.cs
- CmsWeb/Areas/OnlineReg/Controllers/ManageGiving.cs
- CmsWeb/Areas/OnlineReg/Controllers/OnePageGiving.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/PaymentForm.cs
Adding validations for One Page Giving and Recurring Givings.
https://trello.com/c/UDyc2avt/5597-bug-getting-error-when-updating-giving-amount-and-changing-from-a-bank-account-to-a-credit-card
> Fix Recurring Vault Id Issue

- UnitTests/UtilityExtensionsTests/EnDeCryptTests.cs
- UnitTests/UtilityExtensionsTests/UtilityExtensionsTests.csproj
- UnitTests/UtilityExtensionsTests/app.config
Just a simple unit test for Utility.EnDeCrypt class
> Unit test for Utility Encrypt and Decrypt method

- CmsData/CmsData.csproj
- CmsData/Migrations/20190709_update_archive_content_sp.sql
https://trello.com/c/O7U9nneW/5689-bug-getting-error-when-editing-saved-email-draft
> update archive content sproc to delete keywords

- CmsWeb/Areas/Main/Views/Coupon/Index.cshtml
- CmsWeb/Content/touchpoint/js/Coupons.js
- IntegrationTests/Areas/General/GeneralTests.cs
- IntegrationTests/IntegrationTests.csproj
https://trello.com/c/4RRdvC5v/5694-2-coupon-create-not-working-anna-miller-cottonwood-36851
> Td fix coupon create bug

- CmsWeb/Areas/Org/Views/Org/Settings/GeneralEdit.cshtml
- IntegrationTests/Areas/Manage/AccountTests.cs
- IntegrationTests/Support/AccountTestBase.cs
https://trello.com/c/oCo4kCB8/5677-3-suggestion-wayne-brown-ebcjackson-36743
> add help to edit org settings, layout consistency

- CmsWeb/Areas/OnlineReg/Controllers/ManageGiving.cs
https://trello.com/c/0YXWGe6j/5715-2-recurring-gift-set-up-katie-warren-rushcreek-37033
> show error if no funds chosen, or amount is 0

- CmsWeb/Areas/Dialog/Controllers/GetCheckImageController.cs
- CmsWeb/Areas/Dialog/Views/GetCheckImage/GetCheckImage.cshtml
- CmsWeb/Areas/Finance/Controllers/PostBundleController.cs
- CmsWeb/Areas/Finance/Views/PostBundle/Index.cshtml
- CmsWeb/Areas/Finance/Views/PostBundle/Row.cshtml
- CmsWeb/Areas/OnlineReg/Controllers/Payment.cs
- CmsWeb/Areas/OnlineReg/Controllers/Routing.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/Constructor.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/PaymentForm.cs
- CmsWeb/Code/ViewExtensions.cs
- CmsWeb/Content/touchpoint/js/finance/post-bundle.js
- ImageData/Generated/Context.cs
- UnitTests/CMSWebTests/Areas/OnlineReg/Models/OnlineReg/PaymentFormTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
- UnitTests/CMSWebTests/Code/ViewExtensions2Tests.cs
- UnitTests/UtilityExtensionsTests/Extensions/UtilTests.cs
- UnitTests/UtilityExtensionsTests/UtilityExtensionsTests.csproj
- UtilityExtensions/Extensions/TypeConversions.cs
https://trello.com/c/bpw3mDki/5716-hpumc-add-toggle-to-show-all-check-images-inline-on-the-contribution-bundle
> Toggle check images inline with post bundle edit

- CmsData/Classes/OnlineRegSummaryText/Details2.xml
- CmsData/Classes/OnlineRegSummaryText/SummaryInfo.cs
- CmsData/CmsData.csproj
- CmsData/Generated/RecReg.cs
- CmsData/Generated/Views/RegsettingOption.cs
- CmsData/Migrations/20190620_add_passport_reg_setting.sql
- CmsData/Registration/Ask.cs
- CmsWeb/Areas/Manage/Models/BatchModel/BatchRegOptions.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Enroll.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/OnlineRegPersonModel.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/OtherInfo.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/RepopulateRegistration.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/ValidateModelQuestions.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Flow2/QuestionsDisplay.cshtml
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Flow2/QuestionsEdit.cshtml
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Flow2/QuestionsHidden.cshtml
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Other/RegPeople.cshtml
- CmsWeb/Areas/Org/Controllers/Org/Settings/Questions.cs
- CmsWeb/Areas/Org/Views/Org/Registration/QuestionsEdit.cshtml
- CmsWeb/Areas/Reports/Models/Enrollment/RegistrationResult.cs
- CmsWeb/Code/SmartBinder.cs
https://trello.com/c/3KwV7kij/5587-new-registration-field-types-hpumc
> Adding Passport Registration Question

- CmsWeb/Areas/OnlineReg/Controllers/Payment.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/HelperMethods.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/OnlineRegModel.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/PaymentForm.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Other/RegPeople.cshtml
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Other/Terms.cshtml
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Payment/Process.cshtml
- CmsWeb/Areas/Org/Models/Org/SettingsMessagesModel.cs
- CmsWeb/Content/touchpoint/js/onlinereg/OnlineRegPayment2.js
Adding a signature input field to agree to terms and conditions in registrations. The signature can be checked in Registration Data.
> Adding Terms Signature for Registrations

- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
- CmsWeb/Web.config
A tiny change to fix Pushpay issues. The other thing we need to check it's the giving link in the production web.config
> Pushpay fixes

- UtilityExtensions/Extensions/TypeConversions.cs
> This change is necessary for SQLite conversion - concord church

- CmsWeb/Areas/Dialog/Controllers/OrgMemberDialogController.cs
- CmsWeb/Areas/Dialog/Models/OrgMember/OrgMemberModel.cs
- CmsWeb/Areas/Dialog/Views/OrgMemberDialog/Tabs/Questions.cshtml
- CmsWeb/Areas/Reports/Models/Enrollment/RegistrationResult.cs
- CmsWeb/Areas/Reports/Models/Export/ExcelExportModel.cs
- CmsWeb/Content/touchpoint/js/org/organization.js
Add Editable Passport section in Organization Member Dialog
Add Term Signature Name in Registration Report and Registration Report (Excel)
https://trello.com/c/3KwV7kij/5587-new-registration-field-types-hpumc
> Passport Editable Member Dialog

- CmsWeb/Areas/Dialog/Models/OrgMember/OrgMemberModel.cs
Validates if RecReg is not null
Validates if org setting has the passport question
> Passport Member Dialog Fix

- CmsWeb/Areas/Manage/Controllers/SMSController.cs
This fixes the error in SMS Message page
https://trello.com/c/v9TFVwG8/5798-bug-red-page-error-message-when-trying-to-access-sms-messages-page
> Change SMSController base controller to CmsStaffController

- CmsWeb/Areas/Dialog/Controllers/OrgDropController.cs
- CmsWeb/Areas/Dialog/Models/OrgDrop.cs
- CmsWeb/Areas/Manage/Controllers/OrgMembersController.cs
- CmsWeb/Areas/Manage/Models/OrgMembersModel.cs
- CmsWeb/Areas/Org/Controllers/Org/OrgPeople.cs
- CmsWeb/Areas/Org/Controllers/Org/Settings/Attendance.cs
- CmsWeb/Areas/Org/Controllers/OrgGroupsController.cs
- CmsWeb/Areas/Org/Controllers/OrgSearchController.cs
- CmsWeb/Areas/Org/Models/Org/OrgPeopleModel.cs
- CmsWeb/Areas/Org/Models/Org/OrganizationModel.cs
- CmsWeb/Areas/Org/Models/Org/SettingsAttendanceModel.cs
- CmsWeb/Areas/Org/Models/OrgGroupsModel.cs
- CmsWeb/Areas/Org/Models/OrgSearchModel.cs
- CmsWeb/Areas/Reports/Controllers/ReportsController.cs
- CmsWeb/Areas/Search/Controllers/QueryController.cs
- CmsWeb/Areas/Search/Controllers/RegistrationSearchController.cs
- CmsWeb/Areas/Search/Controllers/SavedQueryController.cs
- CmsWeb/Areas/Search/Models/Query/Model/QueryModel.cs
- CmsWeb/Areas/Search/Models/Query/Model/QueryResults.cs
- CmsWeb/Areas/Search/Models/RegistrationSearch/RegistrationSearchModel.cs
- CmsWeb/Areas/Search/Models/SavedQuery/SavedQueryModel.cs
- CmsWeb/CMSWeb.csproj
- CmsWeb/Code/SmartBinder.cs
- CmsWeb/Lifecycle/RequestManager.cs
- CmsWeb/Models/DbBinder.cs
- IntegrationTests/Areas/General/TestQueryController.cs
- IntegrationTests/IntegrationTests.csproj
- UnitTests/CMSWebTests/Areas/Org/Models/TestOrgGroupsModel.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
- UnitTests/SharedTestFixtures/DatabaseFixture.cs
Replaces PR https://github.com/bvcms/bvcms/pull/622
> Assign current database during model binding

- CmsWeb/Content/touchpoint/js/search/saved-query-list.js
https://trello.com/c/km2Hzi1k/5794-2-saved-searches-nancy-duncan-hope-umc-37652
> saved search pagination

- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/AddNew.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/DynamicData.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Enroll.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/OnlineRegPersonModel.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/OtherInfo.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/PrepareSummaryText.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/RepopulateRegistration.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Transaction.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Other/RegPeople.cshtml
- CmsWeb/Views/Script/PyScript.cshtml
> Fix DB Context references

- CmsWeb/App_Start/ApiAuthorizeAttribute.cs
- CmsWeb/Areas/Manage/Controllers/AccountController.cs
- CmsWeb/Areas/Manage/Models/AccountModel.cs
- CmsWeb/Areas/People/Controllers/Person/AdminController.cs
- CmsWeb/Areas/People/Controllers/Person/EnrollmentController.cs
- CmsWeb/Areas/People/Controllers/Person/PersonController.cs
- CmsWeb/Areas/People/Controllers/Person/SystemController.cs
- CmsWeb/Areas/People/Models/Task/TaskModel.cs
- CmsWeb/Areas/Search/Models/SearchAdd/SearchAddModel.cs
- CmsWeb/Code/AuthHelper.cs
- CmsWeb/Code/CmsController.cs
- CmsWeb/Global.asax.cs
- IntegrationTests/Support/Settings.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
- UnitTests/CMSWebTests/Controllers/Api/CustomControllerTests.cs
- UtilityExtensions/Extensions/Util.ConnectionStrings.cs
- UtilityExtensions/Extensions/Util.Session.cs
This is a fix for /CustomAPI which isn't getting the current roles for the user that is authenticated.
> Refactor session objects

- CmsWeb/Areas/Reports/Models/Directories/CompactDir.cs
Report generator was trying to get the first element of an empty string array,
> Fix Compact Directory Bug

- CmsWeb/Content/touchpoint/js/admin/users-email-for.js
https://trello.com/c/x6RFWnfk/5675-email-delegation-bug-2-i-cant-add-a-user-who-can-email-ryanne-caldwell-2pc-36734
> email delegation stability improvements

- CmsData/CmsData.csproj
- CmsData/Generated/Context.cs
- CmsData/Generated/Functions/PledgesSummary.cs
- CmsData/Migrations/20190828_Create_Func_PledgesSummary.sql
- CmsWeb/Areas/Finance/Models/PostBundleModel.cs
- CmsWeb/Content/touchpoint/js/finance/post-bundle.js
- CmsWeb/Content/touchpoint/lib/bootstrap-editable/css/bootstrap-editable.css
- UnitTests/CmsDataTests/Generated/CMSDataContextFunctionTests.cs
- UnitTests/CmsDataTests/Support/FinanceTestBase.cs
Feature request related to this card
https://trello.com/c/UyzLU9PT/5574-display-outstanding-pledges-when-posting-contributions
> Show Outstanding Pledges in Bundle Page

- CmsWeb/Areas/Reports/Models/Export/ExcelExportModel.cs
- UnitTests/CMSWebTests/Areas/Reports/Models/Reports/Export/ExportInvolvementsTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
- UnitTests/CMSWebTests/TestUtils/FakeOrganizationUtils.cs
https://trello.com/c/nmzm2nnz/5711-bug-directory-includes-deceased-children-2-photo-directory-westendcrc-37008
> picture directory update

- CmsData/Classes/ProtectMyMinistry/ProtectMyMinistryHelper.cs
- CmsWeb/Areas/People/Controllers/VolunteeringController.cs
- UnitTests/CmsDataTests/Classes/ProtectMyMinistryHelperTests.cs
- UnitTests/CmsDataTests/CmsDataTests.csproj
Send background check label in BillingReference to show in PMM invoices.
> Background Check Labels Fix

- CmsWeb/Areas/Setup/Controllers/PushpayController.cs
New URL hides Recurring Giving option when you are in a one time giving or registration process.
> Pushpay URL Fix

- CmsWeb/Areas/Org/Controllers/MissionTripEmailController.cs
https://trello.com/c/5dCPzj7t/5842-bug-email-supporters-button-not-working-for-mydata-users-2-missions-trip-pages-debbie-hoffman-friendshipmn-38150
> allow mydata users to email supporters

- CmsWeb/Areas/Org/Views/Org/Settings/CheckIn.cshtml
- CmsWeb/Areas/Setup/Views/Roles/Manage.cshtml
- CmsWeb/Content/touchpoint/js/form-ajax.js
- CmsWeb/Views/Shared/_Layout.cshtml
- IntegrationTests/Areas/Org/Views/Org/SettingsViewsTests.cs
- IntegrationTests/IntegrationTests.csproj
- UnitTests/SharedTestFixtures/DatabaseTestBase.cs
https://trello.com/c/MR8iMZFJ/5853-2-settingscheckinsave-button-sue-mayes-crosschurch-38236
> show confirmation after saving org checkin settings

- CmsWeb/Areas/Dialog/Controllers/AddOrganizationController.cs
Avoid overwriting settings when settings were copied
https://trello.com/c/PJpQr8wd/5864-2-copying-org-questions-not-copied-over-kayan-wong-redeemer-38306
> Copy Org Settings Fix

- CmsWeb/App_Start/WebApiConfig.cs
- CmsWeb/Areas/Manage/Controllers/DisplayController.cs
- CmsWeb/Areas/People/Models/Person/PictureResult.cs
- CmsWeb/Areas/Reports/Controllers/CustomReportsController.cs
- CmsWeb/Areas/Reports/Controllers/SpecialReportViewModel.cs
- CmsWeb/Areas/Reports/Models/Other/CustomReportsModel.cs
- CmsWeb/Web.config
- IntegrationTests/Areas/Reports/Views/Reports/ApplicationTests.cs
- IntegrationTests/Areas/Reports/Views/Reports/ReportsViewTestsResources.resx
Also added some activity logging for reports and content.
> Fix OData filter/page/count/sort operations, refactoring

- CmsWeb/Areas/Reports/Models/Export/ExportPeople.cs
- UnitTests/CMSWebTests/Models/ExportPeopleTest.cs
* CMSWeb: remove ContributionTypeID from export.
* UnitTest: removing count on ContributionTypeID since it is not being exported.
> Ja duplicated donor exported

- CmsCheckin/CmsCheckin.csproj
- CmsData/CmsData.csproj
- CmsData/Properties/Resources.resx
- CmsWeb/Resource1.resx
- CmsWeb/gulpfile.js
- ImageData/ImageData.csproj
- UnitTests/ImageDataTests/Resources/ImageDataTestsResources.resx
- UtilityExtensions/UtilityExtensions.csproj
We are a group of Linux enthusiasts in Germany who are members of various churches (https://luki.org/).
We are currently investigating bvcms, to see if it would work for German churches.
During this investigation, we are trying to build and run bvcms on Linux with Mono.
This Pull Request is just a small step, but should not affect the build on Windows at all.
We just replaced System.configuration with System.Configuration in some csproj files, and fixed paths and filename in resource files, and fixed the path Content in the gulpfile.
More work is in my fork at: https://github.com/SolidCharity/bvcms/tree/TP-20191017-build-fedora30
But that is not ready for a pull request at all. Just to let you know...
> fix capitalization as a first step to build on Linux

- CmsData/QueryBuilder/Condition.cs
- CmsData/QueryBuilder/FieldClass.cs
- CmsData/QueryBuilder/QueryParser.cs
- CmsData/QueryBuilder/Serialize2.cs
- CmsWeb/Areas/Search/Models/Query/Model/QueryModel.cs
- CmsWeb/Areas/Search/Models/Query/Model/SelectLists.cs
- CmsWeb/Areas/Search/Models/Query/Model/Visibility.cs
- CmsWeb/Areas/Search/Views/Query/EditCondition.cshtml
- CmsWeb/Code/CodeValueModel.cs
Please do not review the code until you view the video.
> Add member type and attend type listboxes

- CmsWeb/Areas/Dialog/Models/OrgMember/OrgMemberModel.cs
https://trello.com/c/zXOpvD8y/5900-2-mission-trip-goer-issue-staci-patyrak-hpumc-38533
and
https://trello.com/c/h7WDP2e1/5923-2-access-to-mission-trip-payments-melanie-grant-canopyroads-38657
> fix member dialog popup with no passport

- CmsWeb/Areas/Search/Models/PictureDirectoryModel.cs
https://trello.com/c/qbDVRY1G/5948-bug-unable-to-search-for-names-with-apostrophe-in-picture-directory-on-ios
> trim search input on picture directory search

- CmsWeb/Areas/Finance/Controllers/ContributionsController.cs
- CmsWeb/Areas/Finance/Models/ContributionSearchModel.cs
- IntegrationTests/Areas/Figures/Views/Figures/RefineFundViewTests.cs
- UnitTests/CmsDataTests/API/APIContributionSearchModelTests.cs
- UnitTests/CmsDataTests/CmsDataTests.csproj
Passing SearchInfo in the APIContributionSearchModel
Undo last change
https://trello.com/c/ri9DNfv7/5959-2-contributions-search-pagination-not-working-kayan-wong-redeemer-38878
> Contribution Pagination Fix

- CmsWeb/Areas/Manage/Models/TransactionsModel.cs
https://trello.com/c/uDywPh7N/5961-2-15-mission-trips-funding-page-links-not-working-unless-already-logged-in-anna-miller-cottonwood-38890#
> model can be instantiated without a user session

- CmsWeb/Areas/CheckIn/Models/CheckinTimeModel.cs
- CmsWeb/Areas/Figures/Views/Figures/AttendanceChartDisplayView.cshtml
- CmsWeb/Areas/Figures/Views/Figures/ChartDisplayView.cshtml
- CmsWeb/Areas/Figures/Views/Figures/FundView.cshtml
- CmsWeb/Areas/Figures/Views/Figures/RefineAttendanceView.cshtml
- CmsWeb/Areas/Figures/Views/Figures/RefineFundView.cshtml
- CmsWeb/Areas/Manage/Models/AccountModel.cs
- CmsWeb/Areas/Setup/Controllers/SettingController.cs
- CmsWeb/CMSWeb.csproj
- CmsWeb/Code/ViewExtensions.cs
- CmsWeb/Content/touchpoint/js/figures/figures.js
- CmsWeb/Content/touchpoint/js/main.js
- CmsWeb/Membership/MembershipService.cs
- CmsWeb/Views/Shared/Account/_Layout.cshtml
- CmsWeb/Views/Shared/Account/_ShellLayout.cshtml
- CmsWeb/Views/Shared/OnlineReg2.cshtml
- CmsWeb/Views/Shared/_Layout.cshtml
- CmsWeb/Views/Shared/_LayoutCheckIn.cshtml
- CmsWeb/Views/Shared/_LayoutNoHeaderFooter.cshtml
- CmsWeb/Views/Shared/_diagnostics.cshtml
- IntegrationTests/Areas/CheckIn/Views/CheckinTimeViewsTests.cs
- IntegrationTests/Areas/Figures/Views/Figures/RefineFundViewTests.cs
- IntegrationTests/Areas/General/QueryControllerTests.cs
- IntegrationTests/Areas/Search/Models/SavedQueryInfoTest.cs
- IntegrationTests/IntegrationTests.csproj
- IntegrationTests/Support/FeatureTestAttribute.cs
- IntegrationTests/Support/FeatureTestBase.cs
https://trello.com/c/OqSAoX7v/5973-update-google-apis-library-loader
This update should fix several flaky tests and multiple references to javascript files (double downloading)
> Fix javascript-related issues in tests

- CmsData/Migrations/20191108_Checkin-performance-improvements.sql
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAccount.cs
- UnitTests/CMSWebTests/Areas/Public/Controllers/CheckInAPIControllerTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
https://trello.com/c/n7Iyf5dV
- Removed the use of a temp table when recording attendance
- Optionally offload some of the work to update attendance summaries
> Checkin performance improvements

- CmsData/API/APIContributionSearchModel.cs
- CmsWeb/Areas/Finance/Models/ContributionSearchModel.cs
- CmsWeb/Areas/Finance/Views/Contributions/Index.cshtml
https://trello.com/c/i4iFf1gE/6036-pushpay-filter-on-contribution-search#
> add pushpay filter to contributions search

- CmsData/Generated/PrintJob.cs
- CmsData/Migrations/20191212_Checkin-print-jobs-pk.sql
- CmsWeb/Areas/OnlineReg/Controllers/ManageGiving.cs
- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
- CmsWeb/Areas/OnlineReg/Controllers/SetHeaders.cs
- CmsWeb/Areas/Public/Controllers/APICheckin2Controller.cs
- CmsWeb/Areas/Public/Controllers/CheckInAPIv2Controller.cs
- CmsWeb/Areas/Public/Models/CheckIn/CheckInModel.cs
- CmsWeb/Areas/Public/Models/CheckIn/FamilyResult.cs
- UnitTests/CMSWebTests/Areas/Public/Models/CheckIn/CheckInModelTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
> OnlineReg/ManagedGiving campus-specific shell fix and check-in print jobs refactor

- CmsWeb/Areas/Main/Views/Email/Compose.cshtml
Added the existing special links button / modal to the legacy CKEditor email modal window.
> Special Links Button / Modal

- CmsData/API/PythonModel/PythonModel.Contributions.cs
- CmsData/Extensions/Contribution.cs
https://trello.com/c/hQN1Lm3J/6065-2-contributions-import-ron-pruet-bethelofhouston-39609
> Add bundle total description to python contributions

- CmsData/CmsData.csproj
- CmsData/Extensions/SettingMetadatum.cs
- CmsData/Generated/SettingMetadatum.cs
- CmsData/Migrations/20200114_Update-func-PledgeBalances-negative-balance.sql
- CmsWeb/Areas/People/Controllers/Person/GivingController.cs
- CmsWeb/Areas/People/Models/Person/Giving/ContributionsModel.cs
- CmsWeb/Areas/People/Views/Person/Giving/Contributions.cshtml
- CmsWeb/Areas/Setup/Views/Setting/_Settings.cshtml
https://touchpointsoftware.atlassian.net/browse/TPD-327?atlOrigin=eyJpIjoiOTcxYzk4NzViNjMzNGQwYmEyODVmMzZkOTcwZGM5NTYiLCJwIjoiaiJ9
> TPD-327 Negative pledge balance option

- CmsData/CmsData.csproj
- CmsData/Generated/Context.cs
- CmsData/Generated/SessionValue.cs
- CmsData/Migrations/20200115_Saving-onlineregmodel-without-using-session.sql
- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/CompleteRegistration.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/PaymentForm.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/Payment/Process.cshtml
- CmsWeb/Global.asax.cs
- CmsWeb/Resource1.Designer.cs
- CmsWeb/Resource1.resx
- SqlScripts/datascriptTest.sql
- UnitTests/CMSWebTests/Areas/Reports/Models/Reports/Other/MailingControllerTests.cs
- UnitTests/CMSWebTests/TestUtils/ControllerTestUtils.cs
- UnitTests/CmsDataTests/DbUtil/CMSDataContextTests.cs
- UnitTests/SharedTestFixtures/MockHttpContext.cs
- UtilityExtensions/Extensions/UtilityExtensions.cs
- codecov.yml
- deploy.cmd
- test.cmd
https://touchpointsoftware.atlassian.net/browse/TPD-331
> Update method for saving registration state between requests

- CmsWeb/Areas/OnlineReg/Models/OnlineReg/EnrollAndConfirm.cs
- IntegrationTests/Areas/OnlineReg/Models/OnlineReg/EnrollAndConfirmTests.cs
- IntegrationTests/IntegrationTests.csproj
Remove spaces in validation of email recipients
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=6&projectKey=TPD&modal=detail&selectedIssue=TPD-455
> Notify Person Email Fix

- CmsWeb/Areas/People/Views/Person/Emails/Tab.cshtml
- CmsWeb/Code/CmsController.cs
- CmsWeb/Views/Shared/RoleSettingDefaults.xml
Some Custom Access Settings are only working with the OrgLeadersOnly role. 2 User Roles: Anna Miller @ cottonwood [37912]
https://trello.com/c/eXSa8EIK/5835-some-custom-access-settings-are-only-working-with-the-orgleadersonly-role-2-user-roles-anna-miller-cottonwood-37912
Fixing customs settings for
General > Home Page
Person > Ministry Tab
Person > Email Details
> Customs settings fix

- CmsData/DbUtil/Context.cs
- CmsData/DbUtil/Session.cs
- CmsWeb/Areas/Manage/Models/AccountModel.cs
- CmsWeb/Areas/OnlineReg/Models/OnlineReg/HelperMethods.cs
- CmsWeb/Areas/People/Controllers/Person/GivingController.cs
- CmsWeb/Areas/People/Controllers/Person/PersonController.cs
- CmsWeb/Areas/People/Controllers/Person/SystemController.cs
- CmsWeb/Areas/People/Models/Person/PersonModel.cs
- CmsWeb/Areas/Public/Controllers/APICheckin2Controller.cs
- CmsWeb/Controllers/Home2Controller.cs
- CmsWeb/Controllers/HomeController.cs
- CmsWeb/Views/Home/UserPreferences.cshtml
- IntegrationTests/IntegrationTests.csproj
- UtilityExtensions/Extensions/Util.Session.cs
- UtilityExtensions/Extensions/UtilityExtensions.cs
Relates to https://touchpointsoftware.atlassian.net/browse/TPD-489 and https://touchpointsoftware.atlassian.net/browse/TPD-481
> Clean up session usage

- CmsData/DbUtil/Context.cs
> TPD-253 Adds RetrieveBatchData function to CmsData for reusability

- CmsWeb/package.json
- IntegrationTests/Areas/Figures/Views/Figures/RefineFundViewTests.cs
- IntegrationTests/Areas/Manage/AccountTests.cs
- IntegrationTests/Areas/People/Views/Person/PersonViewsTests.cs
- IntegrationTests/Areas/Reports/Views/Reports/ApplicationTests.cs
- IntegrationTests/Areas/Search/Views/Query/EditConditionTests.cs
- IntegrationTests/Areas/Setup/SetupTests.cs
- IntegrationTests/Support/FeatureTestAttribute.cs
- IntegrationTests/WebAppFixture.cs
- README.md
- UnitTests/CMSWebTests/Areas/Public/Models/SmallGroupFinderModelTests.cs
- use older gulp-less that avoids the accord library
- update clr script instructions
> fixes 2 issues i had on a fresh install

- CmsData/DbUtil/Context.cs
https://touchpointsoftware.atlassian.net/browse/TPD-253
> TPD-253 Adds AutoSyncBatchDatesWindow setting to automatic batch check

- CmsWeb/Areas/Manage/Models/TransactionsModel.cs
(checkbox / filter option) https://touchpointsoftware.atlassian.net/browse/TPD-252
> TPD-252 Removes check to pull in batch dates from 'Use batch dates'

- CmsData/Finance/Acceptiva/Transaction/Get/GetSettledTransDetails.cs
- CmsData/Finance/AcceptivaGateway.cs
This one is to test the Acceptiva API response in live environment.
> Acceptiva Batch Dates Refactor

- CmsData/Generated/Context.cs
- CmsData/Migrations/20200226_Alter_GetTotalContributionsDonor2.sql
- CmsWeb/Areas/Manage/Controllers/TransactionsController.cs
- CmsWeb/Areas/Manage/Models/TransactionsModel.cs
- CmsWeb/Areas/Manage/Views/Transactions/Index.cshtml
- CmsWeb/Areas/Org/Controllers/Org/Settings/General.cs
- CmsWeb/Areas/Org/Views/Org/DisplayTemplates/ESpaceEventId.cshtml
- CmsWeb/Areas/Org/Views/Org/EditorTemplates/ESpaceEventId.cshtml
- CmsWeb/Areas/Org/Views/Org/Other/eSpaceResults.cshtml
- CmsWeb/Areas/Reports/Models/Export/ExportPeople.cs
- UnitTests/CMSWebTests/Areas/Reports/Models/Export/ExportPeopleTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
- UnitTests/CmsDataTests/Generated/CMSDataContextFunctionTests.cs
- eSpaceClient/Services/eSpaceServiceBase.cs
https://touchpointsoftware.atlassian.net/browse/TPD-610?atlOrigin=eyJpIjoiOGQ4YmMwYmE3Y2VlNDJmY2JiNDcwMmYyMjYwOTYzYmQiLCJwIjoiaiJ9
> TPD-610 GetContributionsDetails parameter missed

- CmsWeb/Areas/Manage/Controllers/TransactionsController.cs
- CmsWeb/Areas/Manage/Models/TransactionsModel.cs
- CmsWeb/Areas/Manage/Views/Transactions/Index.cshtml
Removing use of ViewBag.db
Updating Additional Filter properties on TransactionModel
Fising html structure on index
> Fix Transaction Aditional Filters

- CmsWeb/Areas/CheckIn/Views/CheckIn/Index.cshtml
https://touchpointsoftware.atlassian.net/browse/TPD-578
and
https://touchpointsoftware.atlassian.net/browse/TPD-582
> mask checkin admin pin

- CmsData/DbUtil/Context.cs
- CmsWeb/Areas/Manage/Controllers/BatchController.cs
- CmsWeb/Areas/Manage/Views/Batch/RetrieveBatchData.cshtml
- CmsWeb/Content/touchpoint/src/less/utils.less
Per updated requirements on TPD-251 https://touchpointsoftware.atlassian.net/browse/TPD-251
> TPD-251 Updates batch action option to include date range

- CmsWeb/Areas/Search/Controllers/QueryController.cs
- CmsWeb/Content/touchpoint/js/export-toolbar.js
- IntegrationTests/Areas/Search/Views/Query/ResultsTests.cs
- IntegrationTests/IntegrationTests.csproj
https://touchpointsoftware.atlassian.net/browse/TPD-510?atlOrigin=eyJpIjoiOWI3NDA5ZGQ1NTY2NGFmOThmZjA3NTBiZjM4OGE5NDMiLCJwIjoiaiJ9
> TPD-510 Validation and page refresh added

- CmsData/API/APIContributionSearchModel.cs
https://touchpointsoftware.atlassian.net/browse/TPD-607
> TPD-607 Update logic to properly handle nontaxded options.

- CmsWeb/Areas/OnlineReg/Models/OnlineReg/Confirm.cs
https://touchpointsoftware.atlassian.net/browse/TPD-624
> TPD-624 Fix registration failure under certain conditions

- CmsWeb/Areas/Public/Models/CheckInAPIv2/Family.cs
https://touchpointsoftware.atlassian.net/browse/TPD-585
> checkin - allow search by last, first

- CmsWeb/Areas/CheckIn/Views/CheckIn/Index.cshtml
- CmsWeb/Areas/Public/Models/CheckInAPIv2/Family.cs
- CmsWeb/Areas/Public/Models/CheckInAPIv2/FamilyMember.cs
- CmsWeb/Content/touchpoint/css/checkin.css
also include alt names on class selection screen
https://touchpointsoftware.atlassian.net/browse/TPD-684
> checkin - show members in family on family selection screen

- CmsWeb/Areas/Finance/Models/Statements/ContributionStatements.cs
- CmsWeb/Areas/People/Controllers/Person/GivingController.cs
- CmsWeb/Errors/DatabaseCreationError.aspx
- CmsWeb/Errors/DatabaseNotFound.aspx
- CmsWeb/Errors/DatabaseNotInitialized.aspx
- CmsWeb/Errors/DatabaseServerNotFound.aspx
- CmsWeb/Errors/Error.aspx
- CmsWeb/Errors/PageNotFound.aspx
- README.md
https://touchpointsoftware.atlassian.net/browse/TPD-718
> TPD-718 Fix legacy column widths for 2-column statements

- CmsData/CmsData.csproj
- CmsData/Migrations/20200311_AddSettingMetaData_BundleEntryCampusCode.sql
- CmsWeb/Areas/Finance/Controllers/PostBundleController.cs
- CmsWeb/Areas/Finance/Models/PostBundleModel.cs
This optionally adds a campusid beside the age on the name search.
https://touchpointsoftware.atlassian.net/browse/TPD-566
> TPD-566 BundleEntryCampusCode setting option

- CmsData/API/APIContribution.cs
- CmsData/API/APIContributionSearchModel.cs
- CmsData/CmsData.csproj
- CmsData/Generated/Campu.cs
- CmsData/Generated/Contribution.cs
- CmsData/Migrations/20200312_AddSettingMetaData_ContributionsCampusColumn.sql
- CmsData/Migrations/20200312_Add_FK_Contribution_Campus.sql
- CmsWeb/Areas/Finance/Models/ContributionSearchModel.cs
- CmsWeb/Areas/Finance/Views/Contributions/Results.cshtml
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAccount.cs
Must be sortable from header link
Enabled by setting called ContributionsCampusColumn
https://touchpointsoftware.atlassian.net/browse/TPD-567
> TPD-567 Add CampusCode optionally to Contribution Search Results

- CmsData/QueryBuilder/Expressions/AttendanceHistory.cs
- CmsData/QueryBuilder/FieldMap.csv
This replaces pull request #777.
> Another change to GetEldestFamilyMember to change filtering for Member Type and Attend Type

- CmsData/API/APIContributionSearchModel.cs
- CmsData/CmsData.csproj
- CmsData/Generated/Context.cs
- CmsData/Migrations/20200318_alter_ContributionSearch_func.sql
- CmsData/Migrations/20200318_alter_GetTotalContributionsDonorFund_func.sql
- CmsData/Migrations/20200319_alter_GetContributionsDetails_func.sql
- CmsWeb/Areas/Finance/Models/ContributionsExcelResult.cs
- CmsWeb/Areas/Finance/Models/TotalsByFundModel.cs
- CmsWeb/Areas/Reports/Models/Export/ExportPeople.cs
- UnitTests/CMSWebTests/Areas/Reports/Models/Export/ExportPeopleTests.cs
Include pledges in TotalsByFund seach model
Updating API Contribution Search
Updating ContributionSearch and GetTotalContributionsDonorFund SQL functions
Updating parameters on Excel Export to function according with IncludePledge and Online flags.
Updating ExportPeopleTest
> TPD-407, TPD-628, TPD-627, TPD-640

- CmsData/Migrations/20200324_alter-OrgMemberDocuments-default-createddate.sql
- CmsWeb/Areas/Dialog/Models/OrgDrop.cs
- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- UtilityExtensions/Extensions/Util.Session.cs
https://touchpointsoftware.atlassian.net/browse/TPD-685
https://touchpointsoftware.atlassian.net/browse/TPD-742
> TPD-742 drop org members and TPD-685 Member dialog won't load

- CmsData/Finance/MultipleGatewayUtils.cs
- CmsWeb/Areas/Setup/Controllers/PushpayController.cs
- CmsWeb/Web.config
include excpetion in authenticity for pushpay methods
> TPD-441 Pushpay Anonymous User Fix

- CmsData/CmsData.csproj
- CmsData/Migrations/20200326_alter-GetContributionsRange-func.sql
- CmsData/Migrations/20200326_alter-GetTotalContributionsAgeRange-func.sql
- CmsData/Migrations/20200326_alter-GetTotalContributionsRange-func.sql
Updating ContributionSearch() function calls.
> TPD-754 Donor Totals By Range report Fix 2

- CmsWeb/Areas/Figures/Views/Figures/Index.cshtml
replaced the hard coded year with html datetime attribute
> TPD-359 Vital Stats Graph has wrong year on labels

- CmsData/QueryBuilder/Expressions/Admin.cs
Updating HasEmailOptout() to be reactive according to comparator.
> TPD-431 Search Conditions - HasOptoutsForEmail Fix

- CmsWeb/Areas/Finance/Models/RemoteDepositCapture.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- UnitTests/CMSWebTests/Areas/Public/Controllers/MobileAPIv2ControllerTests.cs
https://touchpointsoftware.atlassian.net/browse/TPD-502
> TPD-502 - Rework mobile giving history API

- CmsWeb/Areas/Main/Views/Email/Compose.cshtml
- UnitTests/CmsDataTests/CmsDataTests.csproj
- UnitTests/CmsDataTests/Properties/Text/RenderTemplateTest.txt
- UnitTests/CmsDataTests/QueryBuilder/AttendTests.cs
Fixes when saving draft and when selecting draft
> TPD-804 Fix for Saved Draft not saving Subject

- CmsWeb/Areas/Finance/Controllers/StatementsController.cs
- UnitTests/CmsDataTests/API/QueryFunctions/QueryFunctionsTests.cs
- UnitTests/CmsDataTests/CmsDataTests.csproj
https://touchpointsoftware.atlassian.net/browse/TPD-873
> TPD-873 Links broken for previously run statement sets

- CmsWeb/Areas/Org/Views/OrgSearch/Row.cshtml
Access and no Edit, should not be able to Edit fields in OrgSearch results.
> TPD-584 Do not allow OrgSearch edting without Edit role

- CmsWeb/Content/touchpoint/js/finance/post-bundle.js
- IntegrationTests/Areas/Finance/Views/PostBundle/PostBundleViewsTests.cs
- IntegrationTests/IntegrationTests.csproj
Jquery now waits until controller responds.
> TPD 869 - Contribution Split Fix

- CmsWeb/Views/Shared/SearchBox.cshtml
https://touchpointsoftware.atlassian.net/browse/TPD-928
> TPD-928 Quick search on mobile

- CmsData/Migrations/20200422_modify_rolllist_udfs.sql
https://github.com/bvcms/bvcms/compare/develop...jrred:tpd-642?expand=1
> TPD-642 modified three UDFs to filter out deceased people

- CmsData/DbUtil/DbUtil.Context.cs
- CmsData/DbUtil/DbUtil.Session2.cs
- UnitTests/CmsDataTests/DbUtil/CMSDataContextTests.cs
https://touchpointsoftware.atlassian.net/browse/TPD-929
> TPD-929 Orgleadersonly role access denied

- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- CmsWeb/Areas/Public/Models/MobileAPI/MobileAnnualGivingSummary.cs
- UnitTests/CMSWebTests/Areas/Public/Controllers/MobileAPIv2ControllerTests.cs
https://touchpointsoftware.atlassian.net/browse/TPD-937
> TPD-937 Fix giving history summary so stock and online gifts are combined

- CmsWeb/Content/touchpoint/js/main.js
- IntegrationTests/Areas/CheckIn/Views/CheckinTimeViewsTests.cs
- IntegrationTests/Support/FeatureTestBase.cs
https://touchpointsoftware.atlassian.net/browse/TPD-388
> TPD-388 fix mobile date inputs

- CmsWeb/Content/touchpoint/js/finance/post-bundle.js
- IntegrationTests/Areas/Finance/Views/PostBundle/PostBundleViewsTests.cs
Include promises to wait until post contribution finishes.
> TPD-948 Split Contribution Fix

- CmsData/CmsData.csproj
- CmsData/Migrations/20200430_alter-OrgFilterPeople-Function_FixNickName.sql
Incorrect results returned by using first name/last name string to filter by nickname.
https://touchpointsoftware.atlassian.net/browse/TPD-790
> TPD-790 Org member search incorrect results fix

- CmsData/API/PythonModel/PythonModel.Contributions.cs
- CmsWeb/Membership/MembershipService.cs
https://touchpointsoftware.atlassian.net/browse/TPD-872
> TPD-872 Two factor auth token not setting cookie

- CmsWeb/Areas/Finance/Controllers/BundleController.cs
- CmsWeb/Areas/Finance/Controllers/BundlesController.cs
- CmsWeb/Areas/Finance/Views/Bundle/Edit.cshtml
- CmsWeb/Areas/Finance/Views/Bundle/Index.cshtml
- UnitTests/CMSWebTests/Areas/Finance/Models/BundleModelsTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
I had to re work the way routing was functioning. Using partial views was causing routing issues. I changed this to use normal views with default routing. This not only fixes the problem, but now all developers know what to expect with the routing of the views in this section, with this BundleController. Everything works as expected now!
Now I need to write a unit test and this item will be done!
> TPD 892 Closing Bundle not redirecting correctly

- CmsData/Registration/AskCheckboxes.cs
- CmsWeb/Areas/OnlineReg/Views/OnlineReg/EditorTemplates/AskCheckboxesMatrix.cshtml
- IntegrationTests/Areas/Org/Views/Org/EditorTemplates/AskCheckboxesTests.cs
Extend to 4 columns allow for reg checkboxes
Fix checkboxes headers and adjust the size.
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1007&assignee=5e19301c85a8c90ecaca7d44
> TPD-1007 Fix Reg Checkboxes Headers

- CmsData/API/PythonModel/DebugScriptsHelper.cs
- CmsData/API/QueryFunctions/Query.cs
touchpointsoftware.atlassian.net/browse/TPD-692
> TPD-692 Add QuerySqlJsonArray Support for multi-line chart

- CmsData/Migrations/20200505_add_giving_sources_widget.sql
- CmsWeb/Areas/Setup/Views/DashboardWidget/Manage.cshtml
- CmsWeb/Views/Home/Dashboard.cshtml
[touchpointsoftware.atlassian.net/browse/TPD-860](https://touchpointsoftware.atlassian.net/browse/TPD-860)
> TPD-860 giving sources widget

- CmsData/Migrations/20200506_update_checkin_setting_help.sql
[touchpointsoftware.atlassian.net/browse/TPD-945](https://touchpointsoftware.atlassian.net/browse/TPD-945)
> TPD-945 update checkin help text

- CmsData/API/APIContribution.cs
- CmsData/DbUtil/DbUtil.Db.cs
- CmsWeb/Areas/People/Controllers/Person/GivingController.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAuthentication.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileMessage.cs
- UtilityExtensions/Extensions/StringExtensions.cs
- UtilityExtensions/Extensions/UtilityExtensions.cs
[touchpointsoftware.atlassian.net/browse/TPD-502](https://touchpointsoftware.atlassian.net/browse/TPD-502)
> TPD-502 Alternative giving links for mobile

- CmsData/Migrations/20200330_homepage_widgets.sql
- CmsData/Migrations/20200506_add_status_flags_widget.sql
[touchpointsoftware.atlassian.net/browse/TPD-915](https://touchpointsoftware.atlassian.net/browse/TPD-915)
> TPD-915 add status flags widget

- CmsData/Classes/ProtectMyMinistry/ProtectMyMinistryHelper.cs
[touchpointsoftware.atlassian.net/browse/TPD-635](https://touchpointsoftware.atlassian.net/browse/TPD-635)
> TPD-635 Update secure search faith web service url

- CmsData/Generated/MobileAppDevice.cs
- CmsData/Migrations/20200504_Add_AppVersion_column_to_MobileAppDevices.sql
- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAccount.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAuthentication.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileMessage.cs
- CmsWeb/Models/HomeModel.cs
- UnitTests/CMSWebTests/Areas/Public/Controllers/MobileAPIv2ControllerTests.cs
- UnitTests/CMSWebTests/Areas/Public/Models/MobileAPIv2/MobileAuthenticationTests.cs
https://touchpointsoftware.atlassian.net/browse/TPD-901
> TPD-901 Tracking version number for app installs

- CmsData/API/PythonModel/PythonModel.Sms.cs
- CmsWeb/Web.config
- UnitTests/CmsDataTests/API/PythonModel/PythonModelTests.cs
- UnitTests/CmsDataTests/CmsDataTests.csproj
- UnitTests/CmsDataTests/QueryBuilder/MembershipTests.cs
- UnitTests/CmsDataTests/packages.config
Ability to create short urls inside a python script.
touchpointsoftware.atlassian.net/browse/TPD-940
> TPD-940 Add CreateTinyUrl to PythonModel

- CmsData/Migrations/20200330_homepage_widgets.sql
https://touchpointsoftware.atlassian.net/browse/TPD-1003
> TPD-1003 Update blog widget to remove unicode characters

- CmsData/Migrations/20200518_add_widget_giving_metrics.sql
- CmsData/Migrations/20200518_add_widget_giving_to_budget_comparison.sql
- UnitTests/CmsDataTests/Generated/DashboardWidgetsTests.cs
- UnitTests/SharedTestFixtures/MockContent.cs
[touchpointsoftware.atlassian.net/browse/TPD-1020](https://touchpointsoftware.atlassian.net/browse/TPD-1020)
> TPD-1020 Widget Giving Metrics

- CmsWeb/Content/touchpoint/js/checkin.js
- IntegrationTests/Areas/CheckIn/Views/CheckinViewsTests.cs
- IntegrationTests/IntegrationTests.csproj
Fix format issues for Safari browser in Web Checkin
[touchpointsoftware.atlassian.net/browse/TPD-1040](https://touchpointsoftware.atlassian.net/browse/TPD-1040)
> TPD-1040 Safari CheckIn date fix

- CmsData/Migrations/20200516_add-quick-sign-in-settings.sql
[touchpointsoftware.atlassian.net/browse/TPD-656](https://touchpointsoftware.atlassian.net/browse/TPD-656)
> TPD-656 Quick sign-in settings

- CmsData/Migrations/20200521_add_widget_giving_type_breakdown.sql
- UnitTests/CmsDataTests/Generated/DashboardWidgetsTests.cs
- UnitTests/SharedTestFixtures/MockContent.cs
[touchpointsoftware.atlassian.net/browse/TPD-1021](https://touchpointsoftware.atlassian.net/browse/TPD-1021)
> TPD-1021 Widget Giving Type Breakdown

- CmsWeb/Areas/Finance/Controllers/BundlesController.cs
- CmsWeb/Areas/Finance/Views/PostBundle/Row.cshtml
- IntegrationTests/Areas/Finance/Views/PostBundle/PostBundleViewsTests.cs
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-917&assignee=5e19301c85a8c90ecaca7d44
This also contains the fix for TPD-1013
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1013&assignee=5e19301c85a8c90ecaca7d44
[touchpointsoftware.atlassian.net/browse/TPD-917](https://touchpointsoftware.atlassian.net/browse/TPD-917)
[touchpointsoftware.atlassian.net/browse/TPD-1013](https://touchpointsoftware.atlassian.net/browse/TPD-1013)
> TPD-917 Show Check Images In Bundle Person Search, TPD-1013 Creating Bundle directs to Bundle Header page

- CmsWeb/Areas/People/Controllers/Person/PersonController.cs
- CmsWeb/Areas/People/Views/Person/Giving/Tab.cshtml
- CmsWeb/Areas/Search/Controllers/PeopleSearchController.cs
- CmsWeb/Areas/Search/Models/PeopleSearchModel.cs
- CmsWeb/Content/touchpoint/js/people/givingtab.js
[touchpointsoftware.atlassian.net/browse/TPD-1056](https://touchpointsoftware.atlassian.net/browse/TPD-1056)
> TPD-1056 Transfer giving history to surviving spouse

- CmsData/Migrations/20200515_update_login_metrics_widget.sql
https://touchpointsoftware.atlassian.net/browse/TPD-1046
> update login metrics widget

- CmsData/CmsData.csproj
- CmsData/DbUtil/DbUtil.Codes.cs
- CmsData/Extensions/PaymentMethod.cs
- CmsData/Generated/Context.cs
- CmsData/Generated/PaymentMethod.cs
- CmsData/Generated/Person.cs
- CmsData/Migrations/20200517_create-table-paymentmethod.sql
- CmsShared/CmsShared.csproj
- CmsTwilio/CmsTwilio.csproj
- CmsWeb/CMSWeb.csproj
- ImageData/ImageData.csproj
- RepairOrg/RepairOrg.csproj
- TransactionGateway/TransactionGateway.csproj
- UnitTests/CmsDataTests/CmsDataTests.csproj
- UnitTests/CmsDataTests/Extensions/PaymentMethodTests.cs
- UtilityExtensions/UtilityExtensions.csproj
- eSpaceClient/eSpaceClient.csproj
[touchpointsoftware.atlassian.net/browse/TPD-821](https://touchpointsoftware.atlassian.net/browse/TPD-821)
> TPD-821 PaymentMethod schema

- CmsData/CmsData.csproj
- CmsData/DbUtil/DbUtil.Codes.cs
- CmsData/Extensions/ScheduledGift.cs
- CmsData/Generated/Context.cs
- CmsData/Generated/PaymentMethod.cs
- CmsData/Generated/Person.cs
- CmsData/Generated/ScheduledGift.cs
- CmsData/Generated/ScheduledGiftAmount.cs
- CmsData/Migrations/20200304_Add_ContributionFilterDefault_Setting.sql
- CmsData/Migrations/20200517_create-table-paymentmethod.sql
- UnitTests/CmsDataTests/CmsDataTests.csproj
- UnitTests/CmsDataTests/Generated/ScheduledGiftTests.cs
- UtilityExtensions/Extensions/TypeConversions.cs
[touchpointsoftware.atlassian.net/browse/TPD-801](https://touchpointsoftware.atlassian.net/browse/TPD-801)
> TPD-801 Recurring giving schedules

- CmsWeb/Areas/Public/Models/IncomingSmsModel.cs
> Fix duplicate cellphone problem incoming sms

- CmsWeb/Areas/People/Controllers/Person/CommunicationsController.cs
- CmsWeb/Areas/People/Models/Person/Communication/SmsModel.cs
- CmsWeb/Areas/People/Views/Person/Communications/Optouts.cshtml
TPD-1075, TPD-1091
This fixes two bugs reported. It is based on develop. I'll merge it into my SecondPhaseBranch too.
[touchpointsoftware.atlassian.net/browse/TPD-1091](https://touchpointsoftware.atlassian.net/browse/TPD-1091)
[touchpointsoftware.atlassian.net/browse/TPD-1075](https://touchpointsoftware.atlassian.net/browse/TPD-1075)
> TPD-1075, TPD-1091 Fix Optout Confirmation and Showing Messages NotActuallySent on SmsTab

- CmsWeb/Areas/Manage/Views/SMS/ReplyWords.cshtml
- CmsWeb/Areas/People/Controllers/Person/CommunicationsController.cs
- CmsWeb/Areas/People/Models/Person/Communication/SmsModel.cs
- CmsWeb/Areas/People/Views/Person/Communications/Optouts.cshtml
- CmsWeb/Areas/Public/Models/IncomingSmsModel.cs
If ReplyMessage has a trailing space
[touchpointsoftware.atlassian.net/browse/TPD-1085](https://touchpointsoftware.atlassian.net/browse/TPD-1085)
> TPD-1085 Fix Style on ReplyWord input box and None ReplyMessage

- CmsData/Generated/ContributionFund.cs
- CmsData/Migrations/20200622_Update_Contribution_fund_add_end_date.sql
- CmsWeb/Areas/Finance/Views/Fund/Edit.cshtml
- CmsWeb/Areas/Finance/Views/Fund/Index.cshtml
- UnitTests/CMSWebTests/Areas/Finance/ContributionFundTests.cs
- UnitTests/CMSWebTests/Areas/Finance/Models/PostBundleModelTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
[touchpointsoftware.atlassian.net/browse/TPD-1129](https://touchpointsoftware.atlassian.net/browse/TPD-1129)
> TPD-1129 fund management end date

- CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Helper.cs
- IntegrationTests/Areas/OnlineReg/Views/OnlineRegViewsTests.cs
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1123&assignee=5e19301c85a8c90ecaca7d44
[touchpointsoftware.atlassian.net/browse/TPD-1123](https://touchpointsoftware.atlassian.net/browse/TPD-1123)
> TPD-1123 Deceased People In Registrations Fix

- CmsData/CmsData.csproj
- CmsData/Generated/OrgMemberDocument.cs
- CmsData/Generated/OrgTemporaryDocuments.cs
- CmsData/Migrations/20200618_alter_documents_tables.sql
- CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
- UnitTests/CmsDataTests/DbUtil/CMSDataContextTests.cs
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1107&assignee=5e19301c85a8c90ecaca7d44
[touchpointsoftware.atlassian.net/browse/TPD-1107](https://touchpointsoftware.atlassian.net/browse/TPD-1107)
> TPD-1107 Document Name Length Fix

- CmsWeb/Areas/Manage/Models/TransactionsModel.cs
- IntegrationTests/Areas/Manage/Views/Transactions/TransactionsViewTest.cs
- IntegrationTests/IntegrationTests.csproj
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-939&assignee=5e19301c85a8c90ecaca7d44&assignee=UNASSIGNED_USER_ID
[touchpointsoftware.atlassian.net/browse/TPD-939](https://touchpointsoftware.atlassian.net/browse/TPD-939)
> TPD-939 Transactions Log Search Fix

- CmsData/CmsData.csproj
- CmsData/Migrations/20200626_Update_FundStatusId_0_To_2.sql
- IntegrationTests/Areas/Finance/Views/Fund/IndexTests.cs
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1113&assignee=5e19301c85a8c90ecaca7d44
[touchpointsoftware.atlassian.net/browse/TPD-1113](https://touchpointsoftware.atlassian.net/browse/TPD-1113)
> TPD-1113 FundStatusId Fix when 0

- CmsData/CmsData.csproj
- CmsData/DbUtil/DbUtil.Session2.cs
- CmsData/Email/DefaultSmtpClient.cs
- CmsData/Email/Emailer.cs
- CmsData/Email/IEmailClient.cs
- CmsWeb/Areas/Finance/Controllers/BundlesController.cs
- CmsWeb/Areas/Manage/Models/AccountModel.cs
- CmsWeb/Areas/Public/Controllers/MobileAPIv2Controller.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAccount.cs
- CmsWeb/Areas/Public/Models/MobileAPIv2/MobileAuthentication.cs
- CmsWeb/Membership/CMSMembershipProvider.cs
- UnitTests/CMSWebTests/Areas/Public/Controllers/MobileAPIv2ControllerTests.cs
- UnitTests/SharedTestFixtures/DatabaseTestBase.cs
- UnitTests/SharedTestFixtures/MockCMSMembershipProvider.cs
- UnitTests/SharedTestFixtures/Network/EMLReader.cs
- UnitTests/SharedTestFixtures/Network/MockEmailClient.cs
- UnitTests/SharedTestFixtures/SharedTestFixtures.csproj
[touchpointsoftware.atlassian.net/browse/TPD-1166](https://touchpointsoftware.atlassian.net/browse/TPD-1166)
> TPD-1166 uppercase email fails mobile login

- CmsWeb/Areas/Finance/Views/FinanceReports/TotalsByFund.cshtml
- IntegrationTests/Areas/Finance/Views/FinanceReports/TotalByFundViewTests.cs
- IntegrationTests/IntegrationTests.csproj
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1167&assignee=5e19301c85a8c90ecaca7d44
[touchpointsoftware.atlassian.net/browse/TPD-1167](https://touchpointsoftware.atlassian.net/browse/TPD-1167)
> TPD-1167 Hide Donor Details For No Financial Roles

- CmsWeb/Areas/Manage/Controllers/DisplayController.cs
- CmsWeb/Areas/Manage/Controllers/GridResult.cs
- CmsWeb/Areas/Manage/Models/DisplayModel.cs
- CmsWeb/Areas/Manage/Views/Display/EditTemplate.cshtml
- CmsWeb/Areas/Manage/Views/Display/UnLayerCompose.cshtml
- CmsWeb/CMSWeb.csproj
- CmsWeb/Content/touchpoint/js/email/compose.js
Works on  both Unlayer and CkEditor type template
[touchpointsoftware.atlassian.net/browse/TPD-926](https://touchpointsoftware.atlassian.net/browse/TPD-926)
> TPD-926 Clone Email Templates

- CmsCheckin/CommonListNames.cs
- CmsWeb/Areas/Public/Models/CheckIn/NameSearchResult2.cs
- CmsWeb/Areas/Public/Models/CheckInAPIv2/Family.cs
- CmsWeb/Areas/Setup/Controllers/PushpayController.cs
- TransactionGateway/Gateways/PushPay/PushPayConnection.cs
- TransactionGateway/Gateways/PushPay/PushPayResolver.cs
- UnitTests/CMSWebTests/Areas/Public/Models/MobileAPIv2/FamilyTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
[touchpointsoftware.atlassian.net/browse/TPD-1108](https://touchpointsoftware.atlassian.net/browse/TPD-1108)
> TPD-1108 Checkin name search fixes

- CmsData/Email/ReplacementCodes/Links/IsSpecialLink.cs
- CmsData/Email/ReplacementCodes/Links/UnlayerLink.cs
- CmsData/Generated/ContributionFund.cs
- CmsData/Migrations/20200622_Update_Contribution_fund_add_end_date.sql
- CmsWeb/Areas/Giving/Controllers/GivingManagementController.cs
- CmsWeb/Areas/Giving/Controllers/GivingPageController.cs
- CmsWeb/Areas/Giving/Models/GivingPageModel.cs
- CmsWeb/Areas/Giving/Models/GivingPaymentModel.cs
- CmsWeb/Content/touchpoint/js/speciallinks.js
- CmsWeb/Views/SpecialLinks/Index.cshtml
- UnitTests/CMSWebTests/Areas/GivingSettings/GivingPaymentTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
- UnitTests/SharedTestFixtures/MockCampus.cs
[touchpointsoftware.atlassian.net/browse/TPD-936](https://touchpointsoftware.atlassian.net/browse/TPD-936)
[touchpointsoftware.atlassian.net/browse/TPD-812](https://touchpointsoftware.atlassian.net/browse/TPD-812)
> TPD-936 new special link giving pages, TPD-812 Make Processing Error Codes More Clear

- CmsWeb/Areas/People/Views/Person/Enrollment/Registrations.cshtml
This is a new PR for the fix introduced in https://github.com/bvcms/bvcms/pull/955
> Label when viewing does not match label when editing

- CmsWeb/Areas/Finance/Controllers/FinanceReportsController.cs
- CmsWeb/Areas/Finance/Models/TotalsByFundModel.cs
- CmsWeb/Web.config
- UnitTests/CMSWebTests/Areas/Finance/Models/TotalsByFundModelTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1204&assignee=5e19301c85a8c90ecaca7d44
[touchpointsoftware.atlassian.net/browse/TPD-1204](https://touchpointsoftware.atlassian.net/browse/TPD-1204)
> TPD-1204 Filter CustomReport for Finance Role

- CmsWeb/Areas/Finance/Models/TotalsByFundModel.cs
- CmsWeb/Areas/Finance/Views/FinanceReports/TotalsByFund.cshtml
- IntegrationTests/Areas/Finance/Views/FinanceReports/TotalByFundViewTests.cs
https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=TPD&modal=detail&selectedIssue=TPD-1205&assignee=5e19301c85a8c90ecaca7d44&assignee=UNASSIGNED_USER_ID
[touchpointsoftware.atlassian.net/browse/TPD-1205](https://touchpointsoftware.atlassian.net/browse/TPD-1205)
> TPD-1205 Show Donor Details Reports For FundBased Roles Fix

- CmsData/QueryBuilder/CompareClass.cs
- CmsData/QueryBuilder/Condition.cs
- CmsData/QueryBuilder/FieldClass.cs
- CmsWeb/Areas/Search/Models/Query/Model/QueryModel.cs
- CmsWeb/Areas/Search/Views/Query/Conditions.cshtml
- CmsWeb/Areas/Search/Views/Query/SelectCondition.cshtml
- CmsWeb/Content/touchpoint/js/search/query.js
This applies to both the Search dialog for finding a condition as well as the display of conditions in the Query dialog.
[touchpointsoftware.atlassian.net/browse/TPD-1001](https://touchpointsoftware.atlassian.net/browse/TPD-1001)
> TPD-1001 Search Builder to use all Friendly Names

- CmsWeb/Areas/Dialog/Controllers/AddResourceController.cs
- CmsWeb/Areas/Main/Views/Email/Compose.cshtml
- CmsWeb/CMSWeb.csproj
- CmsWeb/Content/touchpoint/js/uploadfile.js
- CmsWeb/Views/SpecialLinks/Index.cshtml
[touchpointsoftware.atlassian.net/browse/TPD-1006](https://touchpointsoftware.atlassian.net/browse/TPD-1006)
> TPD-1006 UploadFile to EmailBuilder

- CmsWeb/Areas/Org/Models/OrgSearchModel.cs
- CmsWeb/Areas/Search/Models/Query/Model/QueryResults.cs
- UnitTests/CMSWebTests/Areas/Org/Models/OrgSearchModelTests.cs
- UnitTests/CMSWebTests/CMSWebTests.csproj
This works on OrgSearch and on SearchBuilder
There is also a UnitTest
[touchpointsoftware.atlassian.net/browse/TPD-568](https://touchpointsoftware.atlassian.net/browse/TPD-568)
> TPD-568 Default Sort By Name on Search Pages
