CmsWeb/Areas/Manage/Models/OrgMembersModel.cs
**Bug Fix**: Originally submitted via TPS Support Request  (gsbcfamily [5717])
**Solution**
The case condition in the Switch statement in ApplySort() should be "Date of Birth"
instead of "DOB" to match the column heading in
CmsWeb/Areas/Manage/Views/OrgMembers/List.cshtml
In the current live build, since it does not find "Date of Birth" it goes to the default which sorts by Name.
``` 
default:
case "Name":
```
**Testing**
I compared performance using same conditions on the life database and a downloaded database with the new build.
=> Fix Org Member Sort

CmsData/Email/EmailReplacements.cs
I am preparing to send out a mass email to everyone that has contributions this year.  I would like to include their statement options in the email for reference.  And encourage them to go online to manage the options as well as to verify contributions and later print out their statements.
I added replacement codes for:
- Electronic Statements  (electronic only or paper)
+ {estatement}
- "Online Electronic Statement Only"
- "Printed Statement in Addition to Online Option"
- Statement Option (Indiv, joint, none)
+ {statementtype}
- "Individual"
- "Joint"
- "None"
- Receive SMS (yes or no)
+ {receivesms}
- "Yes"
- "No"
Here is an example from when I was testing different codes:
=> Email Replacement Codes

CmsData/Email/Emailer.cs, CmsWeb/Areas/Main/Controllers/EmailController.cs
Fixes #87.  Since scheduled emails run in a different process than the web app we should be pulling the CC list from the database rather than a closure.
=> Pull CCs from db rather than from EmailController closure #87

CmsData/CmsData.csproj, CmsData/Finance/TransNational/Transaction/Refund/AchRefundRequest.cs, CmsData/Finance/TransNational/Transaction/Refund/CreditCardRefundRequest.cs, CmsData/Finance/TransNational/Transaction/Void/AchVoidRequest.cs, CmsData/Finance/TransNational/Transaction/Void/CreditCardVoidRequest.cs, CmsData/Finance/TransNationalGateway.cs
So turns out the documentation from TransNational was incorrect and didn't specify that "payment" parameter was needed, but it is required.  Went ahead and add it put into the credit card and ach refund and void requests just incase.
=> Transnational Api Fix

CmsWeb/Areas/Setup/Controllers/SettingController.cs
The [documentation specifies settings](http://docs.touchpointsoftware.com/Administration/CustomHeader.html) such as `UX-HeaderLogo` but the prior regex wouldn't allow for dashes. This should fix that.
=> Allow dash in settings names

CmsWeb/Areas/Manage/Controllers/AccountController.cs, CmsWeb/Areas/Manage/Views/Account/ChangePassword.cshtml, CmsWeb/Areas/Manage/Views/Account/ChangePasswordSuccess.cshtml, CmsWeb/Areas/Manage/Views/Account/ForgotPassword.cshtml, CmsWeb/Areas/Manage/Views/Account/ForgotUsername.cshtml, CmsWeb/Areas/Manage/Views/Account/LinkUsed.cshtml, CmsWeb/Areas/Manage/Views/Account/LogOn.cshtml, CmsWeb/Areas/Manage/Views/Account/RequestPassword.cshtml, CmsWeb/Areas/Manage/Views/Account/RequestUsername.cshtml, CmsWeb/Areas/Manage/Views/Account/ResetPassword.cshtml, CmsWeb/Areas/Manage/Views/Account/SetPassword.cshtml, CmsWeb/Areas/Manage/Views/Account/SetPasswordConfirm.cshtml, CmsWeb/Areas/Manage/Views/Account/_CustomLayout.cshtml, CmsWeb/Areas/Manage/Views/Account/_ShellLayout.cshtml, CmsWeb/CmsWeb.csproj, CmsWeb/Properties/PublishProfiles/work.pubxml
This pull request implements the feature so that the login page (and related views) can be displayed with a custom shell.
If the user sets an admin setting named `UX-LoginPageShell` whose value is the name of HTML special content for a shell, then that shell will be used on the login page.
=> Support custom shells on the login page

CmsWeb/Areas/Org/Views/Org/Toolbar/Gear.cshtml, CmsWeb/CmsWeb.csproj, CmsWeb/Views/ExtraValue/NewStandard.cshtml, CmsWeb/packages.config
This pull request includes the following:
* Use Nuget for EPPlus instead of a direct assembly reference - it resolved a minor compilation issue where CmsWeb and CmsData were using different versions of EPPlus
* Add Volunteer Calendar link for Org Leaders Only when their toolbar view is limited (as in Redeemer's case)
* Fix null reference issue related to the Add Extra Value dialog
Regarding the other issue that Karen reported related to OrgSearch, that was a data issue on staging that I resolved in the special content.
=> Minor bug fixes for Redeemer

CmsWeb/Areas/Public/Models/SmallGroupFinderModel.cs
We inadvertently were only supporting text extra value types in the Small Group Finder! This should fix that - it just coalesces between whichever value is set which is easier in this case as the front end just needs string values.
=> Ensure SGF handles various extra value types

CmsWeb/Areas/Org/Models/OrgSearchModel.cs
Per notes from #130, ensure we handle other extra value types in org search, too.
=> Ensure org search supports various EV types

CmsWeb/Areas/Org/Views/Org/CommunityGroup/CommunityGroup.cshtml, CmsWeb/Areas/People/Views/Person/Index.cshtml, CmsWeb/Areas/Public/Controllers/OrgContentController.cs, CmsWeb/Areas/Public/Models/SGMapModel.cs, CmsWeb/Areas/Public/Models/SmallGroupFinderModel.cs, CmsWeb/Areas/Public/Views/SmallGroupFinder/MapIndex.cshtml
The small group finder had issues when extra values were named with spaces in them - the filter didn't see them and wouldn't show matches. In addition, the replacements wouldn't match either so they didn't work.
The other minor thing is a new admin setting called `UX-HideExtraValueEditForOrgLeaderOnly` that will still let org leaders edit individual extra values, *but* it will prevent them from creating new ones.
=> SGF fixes related to extra values with spaces

CmsWeb/Areas/People/Views/Person/Emails/Emails.cshtml, CmsWeb/Areas/People/Views/Person/Family/Members.cshtml, CmsWeb/Areas/People/Views/Person/Family/Related.cshtml, CmsWeb/Areas/People/Views/Person/Index.cshtml, CmsWeb/Areas/Public/Models/SGMapModel.cs, CmsWeb/Areas/Public/Models/SmallGroupFinderModel.cs, CmsWeb/Areas/Public/Views/SmallGroupFinder/MapContent.cshtml
@davidcarroll FYI, Redeemer has tested these changes on the staging site.
The customizable filtering of organizations on the small group finder is now based on new settings:
```
<SGFSetting name="ShowOnlyName" value="NAME_TO_FILTER_ON" />
<SGFSetting name="ShowOnlyValue" value="VALUE_TO_FILTER_ON" />
```
Basically, it looks for an org extra value named "NAME_TO_FILTER_ON" with a value of "VALUE_TO_FILTER_ON" before it returns it.
In addition, this includes fixes for the ministry tab hiding. I used the same pattern for some other minor admin settings to optionally hide some settings from org leaders.
These settings are:
* `UX-HideEmailDetailsForOrgLeaders`
* `UX-HideQueriesForOrgLeaders`
As I said, this also fixes the prior bug with `UX-HideMinistryTabForOrgLeaders`. The basic boolean …
=> Minor hiding features for org leaders, customizable filtering of which groups are shown on SGF

CmsWeb/Areas/Public/Models/SmallGroupFinderModel.cs
We missed one thing when comparing times (AM/PM) because of a missed hard-coded `"Time"`.
=> Fix issue with SGF time filtering

CmsWeb/Areas/Public/Models/SmallGroupFinderModel.cs
The prior `orderby` wasn't handling the other various types of extra values.
=> Order SGF results by value (while handling various EV types)

CmsWeb/Areas/Public/Models/SGMapModel.cs, CmsWeb/Areas/Public/Views/SmallGroupFinder/MapContent.cshtml
We caught an issue where we were hard-coding the check for marker text. In addition, it didn't support string, code, date, bit, etc. types of extra values.
This adds new SGF settings like below:
```xml
<SGFSetting name="MarkerTextName" value="Group Term" />
<SGFSetting name="MarkerTextValue" value="Beta Group" />
<SGFSetting name="MarkerText" value="B" />
```
Basically, it says if you find the name of `Group Term` for an extra value with a value of `Beta Group` then show `B`.
=> Allow for customization for marker text

CmsWeb/Areas/People/Views/Person/Resources/Tab.cshtml
We missed the dropdown that shows up on mobile responsive views (the whole "visible-xs-block" stuff). As a result, the Resources sub-tabs didn't show up on smaller screens. This fixes it.
=> Fix responsive issue with resources sub tabs

CmsData/Email/Emailer.cs, CmsWeb/Areas/Main/Controllers/EmailController.cs, CmsWeb/Areas/Main/Models/Other/MassEmailer.cs, CmsWeb/Areas/Main/Views/Email/Index.cshtml
A bug was found related to the "Only Prospects" email feature (and the members and prospects list). First off, there is a recipients list that is stored off in hidden fields. It also then uses a hidden field for "only prospects" so that the Emailer doesn't load all recipients up from an org and only relies on the recipient list (which populated the `EmailQueueTos` list).
This was tested on staging and signed off by Redeemer.
=> Email prospect fix

CmsWeb/Areas/Public/Models/OrgContentInfo.cs
I couldn't use `CurrOrgMembers` as is because it also returns prospects and the member only page directory only needs to show members/leaders. I ended up building a LINQ query instead... it seems to perform a lot better now, though, because it is a single query instead of an N+1 issue.
=> Attempt to fix perf issue related to member only page

CmsWeb/Areas/Dialog/Controllers/AddResourceController.cs, CmsWeb/Areas/Dialog/Models/ResourceModel.cs, CmsWeb/Areas/Dialog/Views/AddResource/Index.cshtml, CmsWeb/Areas/Manage/Controllers/AccountController.cs, CmsWeb/Areas/Manage/Controllers/ResourceController.cs, CmsWeb/Areas/Manage/Models/ResourceModel.cs, CmsWeb/Areas/Manage/Views/Resource/Display.cshtml, CmsWeb/Areas/Manage/Views/Resource/Edit.cshtml, CmsWeb/Areas/Org/Models/OrgSearchModel.cs, CmsWeb/Areas/Org/Views/Meeting/Index.cshtml, CmsWeb/Areas/Org/Views/Meeting/Toolbar/Reports.cshtml, CmsWeb/Areas/Org/Views/Meeting/Toolbar/Toolbar.cshtml, CmsWeb/Areas/People/Models/Person/Enrollments/CurrentEnrollments.cs, CmsWeb/Areas/People/Models/Person/Enrollments/PendingEnrollments.cs, CmsWeb/Areas/People/Models/Person/Enrollments/PreviousEnrollments.cs, CmsWeb/Areas/People/Models/Person/PersonModel.cs, CmsWeb/Areas/People/Views/Person/Enrollment/Current.cshtml, CmsWeb/Areas/People/Views/Person/Enrollment/Pending.cshtml, CmsWeb/Areas/People/Views/Person/Enrollment/Previous.cshtml, CmsWeb/Areas/People/Views/Person/Resources/Tab.cshtml, CmsWeb/Content/touchpoint/js/people/person.js, CmsWeb/Views/Shared/PagerTop.cshtml, CmsWeb/Views/Shared/Pagination.cshtml
Hi David - this PR is the follow-up to #171 with the appropriate database changes!
This PR includes the latest requested changes from Redeemer.
Summary of Changes:
* Involvement tab (current, previous and pending)
* Added a new admin setting to allow for hiding the organization type filters
* Allow the previous admin setting we added also define the order of organizations displayed (e.g. if Community Group, Mailing List, Other then display in that order versus in alphabetical order)
* Custom skin for congregation login pages (i.e. campus-specific skins for the login page)
* Follow up items from our last PR to allow for further customization of meeting-pages via XML special content (see #163)
* Allow for Resources to be locked down by status flag
* Added a few minor bug fixes
* the org …
=> Redeemer-Requested Changes

CmsWeb/Areas/People/Views/Person/Resources/Tab.cshtml, CmsWeb/Content/touchpoint/js/people/person.js
Good afternoon David - we found a minor bug with resource sub-tabs _specifically on mobile views_. This fix adds the deep link change so that mobile resource sub tabs work as well.
For a little bit more clarification, this fix is only related to the Resource tab on the Profile page so it will only affect churches that have the Resources feature enabled and are viewing the tab on mobile.
Thanks!
=> Fix Resource Sub-Tabs on Mobile (#93)

CmsWeb/Areas/Org/Models/OrgSearchModel.cs, CmsWeb/Areas/Org/Views/OrgSearch/Results.cshtml, CmsWeb/Areas/Org/Views/OrgSearch/Toolbar/Custom.cshtml
Fixes the following bugs
- Custom Reports when empty shows "No Custom SQL Reports Available" which is too long.
- BUG: Current column on Org Search / Manage page does not sort by current members
=> Changes for Noman bug fix test

CmsWeb/Areas/People/Views/Shared/EditorTemplates/Value.cshtml
White space is usually *not* significant in HTML, but it is if `white-space: pre-wrap` is used. I wouldn't be surprised if some auto formatter even did this. Sorry we missed this!
This will fix https://clearfunction.sifterapp.com/issues/904.
=> Fix issue with multiline extra value display (#120)

CmsWeb/Content/touchpoint/js/people/contact.js
I misread the `localeCompare` docs on this... it should `base`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare for details.
Sorry about that.
=> Fix javascript case sensitivity issue

CmsData/QueryBuilder/Expressions/Contributions.cs
This should fix the problem with MountPisgah Recent Donors not reconciling.
It was a bug in the regular expression to split the values in the Setting Name (with start date).
They have a second parameter to fetch the fundid separated by a comma.
`BridgeSinceDate,BridgeFundId`
Both of these names are for settings in their database.
The second name was returning an empty fundid because of the regex bug.
Trello: Bridge+ Discrepancy when running script reports https://trello.com/c/O8rvfZmp
Please let me know when this is published so that I can let Jeannie know.
=> Fix Condition ContributionAmountSinceSetting

CmsWeb/Areas/People/Views/Person/DisplayTemplates/DeceasedDate.cshtml, CmsWeb/Areas/People/Views/Person/Family/Members.cshtml
Deceased people are highlighted in red but in some areas the css added extra padding unnecessarily
=> Improve deceased person highlighted elements

CmsWeb/Areas/People/Models/Person/Giving/ContributionsModel.cs, CmsWeb/Areas/Reports/Controllers/ExportController.cs, CmsWeb/Views/Shared/Menu/Admin.cshtml
Current Problems:
1. Total by Funds report set does not appear in the menu.
Added menu option, before this was only viewable to the Finance role, but nothing prevented direct navigation to it.
2. The Giving tab on People records is not seen. (This was specifically requested by the client. Should see only designated fund(s) on the Giving tab; should not see non-allowed funds, nor Statements that include all funds.)
Added filters for the contributions that make up the statement and the giving tab based on role membership. The current user can view their own page and see everything or an authorized user clicking on the giving tab would see only those contributions that were to a fund they are authorized for. This has a side effect of meaning that 2 users could see different balances for a …
=> Austin more scoped finance reports

CmsWeb/Areas/Finance/Controllers/PostBundleController.cs, CmsWeb/Areas/Finance/Models/BundleModel.cs, CmsWeb/Areas/Finance/Models/PostBundleModel.cs
Will change the text for the fund dropdown to be dynamic based on the sort option the client is using... ID will display in the front of the name if using the ID to sort or by the name if using the name to sort
https://trello.com/c/QvUkVKW8/5102-sort-funds-by-id-option
=> Fund dropdown text changes

CmsWeb/Areas/People/Views/Person/Personal/Header.cshtml
If no address is present for the record (like in the anonymous donor record that identified this) then you will see a label w/ no address.
=> Adding a null check when rendering the view for "people"

CmsData/Classes/CMSRoleProvider.cs, CmsData/DbUtil/DbUtil.cs, CmsData/DbUtil/Session2.cs, CmsWeb/Areas/Finance/Controllers/StatementsController.cs, CmsWeb/Areas/Finance/Models/ContributionStatementResult.cs, CmsWeb/Areas/Finance/Models/ContributionStatements.cs, CmsWeb/Areas/Manage/Controllers/AccountController.cs, CmsWeb/Areas/Manage/Models/AccountModel.cs, CmsWeb/Areas/OnlineReg/Controllers/Payment.cs, CmsWeb/Areas/People/Views/Person/Giving/CustomStatments.cshtml, CmsWeb/Areas/People/Views/Person/Giving/Statements.cshtml
Fix for https://trello.com/c/TPLknRYo/5140-statements-stuck-running-and-not-generating-statements-under-administration-contributions-statements-for-all-databases
This PR attempts to correct any use, intentional or otherwise of the helper method `DbUtil.Db` so that if it is used outside of an `HttpContext` thread it will have access to a database that was created using `DbUtil.Create(host)`  This whole class really needs to be destroyed but that would impact thousands of lines of code.  Baby steps...
=> Fix for accessing DbUtil.Db outside of an HttpContext thread

CmsWeb/Areas/Finance/Models/TotalsByFundModel.cs, CmsWeb/Code/ModelViewModel.cs
**Reason**
This was brought up during testing of the fund manager code. We currently allow custom reports (sql statements) to be stored and executed and these do not honor the restrictions on funds. The decision, at present, is to not display these reports to users who are members of the FundManager role. This is the modifier role to indicate a user is only authorized for specific funds. 
**Trello**
https://trello.com/c/zyeqZmz6/5032-fund-based-finance-roles#comment-5bad1b9dc9a67b8b5ac85c04
=> Austin fundmanager remove current custom reports

.gitignore, CmsWeb/Areas/OnlineReg/Views/OnlineReg/OnePageGiving/Index.cshtml, CmsWeb/Areas/OnlineReg/Views/OnlineReg/Payment/Process.cshtml, CmsWeb/Content/touchpoint/js/onlinereg/OnlineRegPayment2.js, CmsWeb/Web.config
In OneTimeGiving, and OnePageGiving, "Save Payment Information" checkbox is hidden now when payment information is already saved in DB. If User modifies this payment information checkbox shows up as unchecked forcing the user to consciously check the box if she wants to save it.
=> Daniel save payment box

CmsWeb/Views/Shared/Menu/Admin.cshtml
We've just hidden this administration menu option for anyone except "Developer" role.
This option allows the user to update a bunch of directions through a text CSV layout as follows:
PeopleId	-	-	Address1	Address2	City	StateCode	Zip	-	MoveEffectiveDate
1	-	-	5th Street	NW	Miami	FL	06060	-	10-02-2018
103	-	-	6th Street	NW	Miami	FL	06060	-	10-02-2018
104	-	-	7th Street	NW	Miami	FL	06060	-	10-02-2018
=> Hiding "Upload Addresses" option for everyone except "Developer" role

CmsData/Extensions/Content.cs, CmsWeb/Areas/Manage/Controllers/DisplayController.cs, CmsWeb/Areas/Manage/Models/ContentModel.cs, CmsWeb/Areas/Manage/Views/Display/EditDraft.cshtml, CmsWeb/Areas/Manage/Views/Display/EditHTML.cshtml, CmsWeb/Areas/Manage/Views/Display/EditPythonScript.cshtml, CmsWeb/Areas/Manage/Views/Display/EditSqlScript.cshtml, CmsWeb/Areas/Manage/Views/Display/EditTemplate.cshtml, CmsWeb/Areas/Manage/Views/Display/EditText.cshtml, CmsWeb/Areas/Manage/Views/Display/Index.cshtml
Each file can have one or more keywords added to it via the ContentKeywords table. This table already exists but has never been used. A comma separated list of keywords can be assigned when editing the file. This only applies to HTML, Text, Sql Scripts and Python Scripts files. The Use Case is when you have multiple related files for a special project. Using this feature, you can filter out all the noise of other, unrelated files.
The filter is entered at the top of each list of files on the various tabs. The dropdown to select the keyword is only displayed if there available keywords on files. The filter is stored in a session variable and remains on until specifically removed by selecting the "(not specified)" item in the dropdown list.
When creating a new file while a keyword filter is …
=> Add support to filter Special Content files by keyword

CmsWeb/Areas/People/Models/Person/Giving/ContributionsModel.cs
https://trello.com/c/VRoHRXD3/5192-joint-giving-not-showing-on-givers-records-the-giving-only-shows-on-the-individual-level-on-the-husband-or-wifes-record-but-not
=> Add finance user to logic to view all contributions when looking at the giving tab

CmsWeb/Areas/Public/Models/SGMapModel.cs
I have used all the addresses that the Trello card description mentioned (Including "240 Baldwin Ln, Christiansburg, VA 24073-4414") and all of them have returned the same coordinates and show me the map marker correctly.
However, I noticed something interesting that could be the reason for this issue.
When, for any reason, your API Key is expired or not have permission for Google our application is storing in DB the coordinates 0,0 for that address. Then, when you tried to show the map once again, the application doesn't ask to google for other coordinates but use what is in DB (in this case 0,0) so, doesn't show in the map nor in the groups.
I made a little modification to verify if the coordinates stored are 0,0, if it is the case, then ask again to Google API. I hope this solves the …
=> SFG Map Error

CmsData/Organization/OrganizationMember.cs, CmsWeb/Areas/Dialog/Models/MoveOrgMembersModel.cs, CmsWeb/Areas/Dialog/Models/OrgMember/OrgMemberMoveModel.cs
The process of moving an individual to a different oganization using move member dialog window is fixed running repair transactions in previous organization to remove references in meeting attendance list.
=> Fix member moved from member dialog box.

CmsWeb/Areas/Manage/Views/Display/EditTemplate.cshtml
https://trello.com/c/136fdbQR/5190-email-template-with-role-assigned-to-it-is-giving-everyone-access-instead-of-the-individuals-with-the-specific-role
=> hide name field and role selector from the default email template

CmsData/Finance/Sage/Transaction/TransactionProcessingResponse.cs
There was a null reference exception happening when attempting to retrieve Data.Element("ORDER_NUMBER"). Null values are managed now.
=> Fix null reference exception when consuming xml elements.

CmsData/Extensions/Person.cs, CmsWeb/Models/Api/AddContributionModel.cs
Another spot where the db was passed to the method but the method didn't use the passed db and preferred dbutil.db in a static model method.
https://trello.com/c/pxAWKmos/5274-bug-error-when-using-api-support-tp-re-error-messages
Tested using the gist provided by customer, received following correct response:
{
"peopleId": 9323,
"contributionId": 597630,
"newPerson": false,
"multipleMatches": false,
"source": "txt2give_1083532"
}
=> Add contribution API

CmsData/CmsData.csproj, CmsData/Migrations/20190106_ja-members-null-enrollmentdate-fix.sql
Updating procedure [RepairEnrollmentDate] to take createddate when enrollmentdate is null.
Migration: 20190106_ja-members-null-enrollmentdate-fix.sql
Line 11
*isnull(om.EnrollmentDate, om.createddate)*
=> Fix members with null enrollment date

CmsWeb/Areas/Manage/Models/TransactionsModel.cs
https://trello.com/c/yZ52ygbA/5246-bug-inconsistencies-with-the-reconcile-report-when-using-batch-date
=> Offset days by 7 to allow nonbatched transactions time to settle and be included in reports using batchdates

CmsData/QueryBuilder/Expressions/Contributions.cs
It was possible to see contributions one day ahead in the future out of the date range because an extra 24 hrs were being added both in code and also inside SQL functions. Fixed now.
=> Updating expression ContributionAmountBothJointHistory.

CmsWeb/Areas/Dialog/Controllers/MoveOrgMembersController.cs, CmsWeb/Areas/Dialog/Models/MoveOrgMembersModel.cs
Reduce db trips by putting the long running operation status updates on a separate context avoding SubmitChanges from saving before required.
https://trello.com/c/Nb6D1cGF/5290-slowness-at-bellevue-moving-org-members-is-processing-slowly
=> Performance: Move Org Members

CmsWeb/Areas/Reports/Models/Other/HeadFoot.cs
https://trello.com/c/sgShGIDc/5413-bug-the-recent-attendance-report-is-showing-page-numbers-in-the-footer-from-1-of-7-to-8-of-7-when-there-are-8-pages
=> fix off by 1 error in footer

CmsWeb/Areas/Search/Models/SavedQuery/SavedQueryModel.cs
Support issue.
Trigger: When a header click happens in Saved Search Queries table headers. 
Issue: Object PagedTableModel is executing public method DefineModelList() without assigning admin variable value. Query search was filtering by owner if !admin.
FIX: Set admin value at the beginning of method DefineModelList().
=> Preserving admin variable value when being accessed by objects of type PagedTableModel.

CmsWeb/Areas/People/Views/Person/Personal/Display.cshtml
Well, this ended up being much easier then I was making it out to be... 🤒 This works and reenables the display to designate the record came from online reg. However, unless a user is logged in already during the registration process the user id is still going to be recorded as 0 which means the actual link itself would render an error that says "no person found." Based on the ask, I am assuming this is a desired feature.
I would like to keep the other branch with many more changes in it and continue to refactor this process more there in the future (time permitting when I get caught up). There are many things cleaned up there that I believe would help fix a few intermittent issues with online reg, including possibly submitting some data or running some important methods twice resulting in …
=> Show records with createdby of 0, tag as onlinereg

CmsWeb/Areas/People/Models/Person/Giving/StatementInfo.cs
https://trello.com/c/Xq7oxLPF/5408-bug-internal-server-error-when-going-to-a-persons-giving-statements-page-after-db-configured-to-show-custom-statements-2-help-wi
Out of bounds error if client only has a single fund setup in customstatements. Offset by 1 (ignored by sql) to get correct output.
=> Offset fundhigh by 1 if there is only a single fund present.

CmsWeb/Areas/Reports/Models/Enrollment/RegistrationResult.cs
https://trello.com/c/l8XK3VWw/4471-bug-registration-report-excel-produces-error-when-running-for-previous-members
=> fix null pointer exception when running registration report on previous members of an org

CmsWeb/Controllers/ScriptController.cs
https://trello.com/c/AjaeVa5f/5400-bug-mailchimpsync-python-script-not-producing-data-on-background-page-at-central-presbyterian-church
=> clone db context within worker

CmsWeb/Areas/People/Views/Person/Personal/Display.cshtml
=> Remove online reg designation from person display and return to showing 0 without an error link.

CmsData/API/PythonModel/Internal.cs, CmsData/API/PythonModel/Misc.cs, CmsWeb/Controllers/ScriptController.cs
This will prevent future developers from making the mistake of forgetting to use a Copy of the dbcontext.
I was trying to figure out why the "There is a DataReader already open" error all of a sudden started appearing. 
It turns out it was a side effect of the recently PythonModel constructors passing in the current dbcontext. In some places, the Copy was not being used. The PythonModel should always run on it's own, isolated, dbcontext to prevent side effects from the current dbcontext which may not be finished in the web side.
=> Move Copy() call inside the PythonModel constructor

CmsWeb/Areas/Finance/Models/BatchImport/SubSplashImporter.cs
Match people by email address on subsplash import. Unmatched people remain as previously imported.
=> Subsplash Import - Add people by email

CmsData/DbUtil/CreateDatabase.cs
This was crashing on a script that had a parameter on a line by itself that was called goerAmount (or something like that).
RunScripts was interpreting that as a GO command separator.
=> Fix RegEx bug in RunScripts

CmsWeb/Areas/OnlineReg/Models/OnlineReg/Constructor.cs, CmsWeb/Areas/Org/Views/Org/Dialogs.cshtml
a better solution to https://trello.com/c/ecU3lxR6/5604-1-user-selects-org-registration-set-up-nick-wilbur-ingleside-36214 which preserves the url for sharing
=> add the user email server side, instead of using the query string

CmsWeb/Areas/Setup/Views/Gateway/Index.cshtml, TransactionGateway/TransactionGateway.csproj
We were storing true and false values as 'true' and 'false' (with quotes marks) in GatewayDetails
=> Removing triple quotation marks in MultipleGateway view.

CmsWeb/Areas/OnlineReg/Models/OnlineReg/EnrollAndConfirm.cs, CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/OnlineRegPersonModel.cs, CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Transaction.cs
This is related to Trello card:
https://trello.com/c/AoKgjVaN/5629-1-parkside-church-member-in-ohio-received-a-receipt-from-ingleside-laurie-admin-ingleside-36473
When an organization has set up org id fees and a specific supporter is a member of one of those orgs the system is taking that fees settled instead of the support amount. 
This is why the first Dan Pillot's attempt to donate to Nathan failed.
I just added a fix to avoid using that org id fees when we are doing a mission trip support.
=> Fixing mission trip support when org settings has org id fees

CmsWeb/Content/touchpoint/js/onlinereg/OnlineReg2.js
https://trello.com/c/fmE5aYav/5640-bug-submit-has-to-be-clicked-twice-to-get-to-next-page-on-one-time-giving-page-at-redeemer
=> only add special fund row for a non empty selection

CmsData/Organization/OrganizationMember.cs, CmsWeb/Areas/OnlineReg/Models/OnlineReg/EnrollAndConfirm.cs, CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Enroll.cs, CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/OnlineRegPersonModel.cs, CmsWeb/Areas/OnlineReg/Models/OnlineRegPerson/Transaction.cs
This is related to https://trello.com/c/AoKgjVaN/5629-1-parkside-church-member-in-ohio-received-a-receipt-from-ingleside-laurie-admin-ingleside-36473
Currently, system change org member type to InActive every time a user does a mission trip donation even if the user is an org member already.
=> Fix org member type change

CmsData/Finance/TransNationalGateway.cs, CmsWeb/Areas/OnlineReg/Models/OnlineReg/PaymentForm.cs
https://trello.com/c/UDyc2avt/5597-bug-getting-error-when-updating-giving-amount-and-changing-from-a-bank-account-to-a-credit-card
Validates when TransNational is not returning the vault id. In case we already have 0 stored we request a new vault id.
=> Adding transnational vaultid validation

CmsWeb/Areas/Finance/Models/BundlesModel.cs
https://trello.com/c/SQ0DoTiz/5680-bug-unable-to-sort-by-status-column-on-the-contribution-bundles-page
=> fix sort bundles by id and status functionality

CmsData/API/PythonModel/Person.cs, CmsWeb/Areas/Manage/Models/UpdateFieldsModel.cs, CmsWeb/Areas/Manage/Views/Activity/Results.cshtml, CmsWeb/Areas/People/Models/Person/Changes/ChangesModel.cs
Add `TrackChanges` method to log changes from Update Data by Tag/Query page, following [convention in AddressInfo.cs](https://github.com/bvcms/bvcms/blob/develop/CmsWeb/Areas/People/Models/AddressInfo.cs#L304).
Additionally, add a call to `LogChanges` for Python Scripts in one additional place to match [UpdateCampus](https://github.com/bvcms/bvcms/blob/develop/CmsData/API/PythonModel/Person.cs#L198) and [UpdateMemberStatus](https://github.com/bvcms/bvcms/blob/develop/CmsData/API/PythonModel/Person.cs#L228).
Lastly, mask changes from `PythonModel` as "Admin Scripts" under Profile > System > Changes, which we infer from [the null coalesce to `0` in Person Extensions](https://github.com/bvcms/bvcms/blob/develop/CmsData/Extensions/Person.cs#L1410).
=> Log Changes from Update Data by Tag/Query

CmsWeb/Areas/Org/Controllers/MissionTripEmailController.cs
ViewData.CurrentDatabase was null
Change base controller to CmsStaffController
Add Constructor method passing requestManager to base
Related with this card
https://trello.com/c/jpvTEH4N/5806-mission-trip-email-supporters-button-give-a-red-page-error-object-not-set-to-an-instance-of-an-object
=> Fix MissionTripEmail error page issue

CmsWeb/Areas/Setup/Views/Roles/Manage.cshtml, CmsWeb/Views/Shared/RoleSettingDefaults.xml
deleting CustomAccessRoles.xml now reverts all settings to proper default. this issue had to do with the "reverse" setting which is used to make sure all "Hide"/"Show" are in line in the UI even for settings that are inverted i.e. HidePendingOrgMembers
https://trello.com/c/Hdq7Qimq/5811-2-roles-anna-miller-cottonwood-37853
=> fix default role setting logic

CmsWeb/Areas/Reports/Models/Attendance/MeetingAttendanceModel.cs
Validates if week property is empty
https://trello.com/c/3HHeQwDT/5865-bug-attendance-by-meeting-type-report-returning-error-in-fielder-database
=> Meeting Attendance Report Fix

CmsWeb/Areas/Finance/Controllers/ContributionsController.cs
Taking SearchInfo as parameter instead of ContributionSearchModel
https://trello.com/c/JufKUT54/5957-parameters-on-contribution-search-page-not-working-2-problem-exporting-fund-details-larry-reid-stonyrunfriends-38864
=> Contribution Search Fix

CmsData/Finance/AcceptivaGateway.cs, IntegrationTests/Areas/OnlineReg/OneTimeGivingTests.cs, UnitTests/CmsDataTests/CmsDataTests.csproj, UnitTests/CmsDataTests/Finance/Acceptiva/Core/Helpers/ISO3166Tests.cs
Convert Country to ISO Codes and States to UPS Code which is necessary to complete an Acceptiva ACH transaction.
https://trello.com/c/qV0UdIfh/5295-custom-dev-build-integration-to-acceptiva-for-payment-processing-for-st-ann-parish
=> Acceptiva country code fix

CmsData/API/PythonModel/DebugScriptsHelper.cs, CmsData/API/PythonModel/PythonModel.Misc.cs, CmsData/CmsData.csproj, CmsData/DbUtil/Context.cs, CmsWeb/CMSWeb.csproj, CmsWeb/Content/InstallPyScriptProject.py, CmsWeb/Controllers/ScriptController.cs, CmsWeb/Models/PythonScriptModel.cs, CmsWeb/Models/SqlScriptModel.cs
This method facilitates developing and debugging Python Projects involving multiple file types.
It is intended to be run within Visual Studio against a local database.
However, while not recommended, it will also work with a ConnectionString to a production database.
It is designed to allow you to edit every file locally with your favorite code editor.
I prefer Visual Studio Code rather than mixing in with the normal Visual Studio.
To debug a Python script:
- You must uncheck the *Enable Just My Code* setting
in Tools>Options>Debugging/General area (requires restart I think).
- You must open the file being debugged in the Visual Studio running bvcms.
- You do not need to copy the file to the bvcms project however.  Just open it from Visual Studio. This way, every change made in Visual …
=> Better Python debugging and installation

CmsWeb/Areas/OnlineReg/Controllers/OnlineRegController.cs
Validates current user id is not null to return support page instead of fundraising page.
=> Mission Trip Support Link Fix

CmsData/Organization/OrganizationMember.cs
Enrollment date is not kept after executing member drop . 
Assigning value to the property fixes it.
=> Keep the enrollment date after dropping an organization member.

CmsData/Extensions/Contribution.cs
fixed bug by excluding contribution records with no contribution date. Contribution date in the Contribution table is not null able in the db. Theoretically, therefore, should be no records with  null contribution date. There is one record in the training db in the contribution table with a null in the contribution date.
=> TPD-611 Vital Stats Graphs Error

CmsWeb/Areas/Manage/Models/AccountModel.cs
I changed AuthenticeLogon function to require uu.Person.Deceased == true. If false, this user cannot login. The one question I have is should we do something about the error message? Currently, the error message will say "bad database"
=> TPD-554-Deceased-records-allowed-set-to-recurring

CmsData/Email/Emailer.cs, CmsData/Migrations/20200423_modify_rolllist_udfs.sql, UnitTests/CmsDataTests/CmsDataTests.csproj, UnitTests/CmsDataTests/Email/SendEmailTests.cs
In the Emailer.cs file, the method EmailFinanceInformation(MailAddress fromaddress, Person p, List<MailAddress> list, string subject, string body) would throw an exception if the fromaddress parameter was null (in ManagedGiving, it will be null if Util.TryGetMailAddress() doesn't find the email address).  I added a null check for that.
I also added a unit test for this method, SendEmailTests.cs > Send_Email_Without_From_Address_Does_Not_Throw_Exception()
=> TPD-598 - added null check in EmailFinanceInformation method for missing from address

.gitignore, CmsWeb/Areas/Manage/Controllers/DisplayController.cs, CmsWeb/Web.config, IntegrationTests/Areas/Main/Views/Email/EmailViewsTests.cs
The Example Template (one to the far right) has the property IsUnLayer = true, unlike the other three templates.  This causes UnLayerCompose.cshtml to be rendered, rather than EditTemplate.cshtml like the others.
UnLayerCompose.cshtml calls DisplayController.cs > SaveUnlayerTemplate() when the “Save Template” button is clicked.  The other three templates call DisplayController.cs > ContentUpdate() instead.  That is why they all work (thumbnail image is created and displayed) whereas the Example Template link isn’t working.
So I added the image creation code to SaveUnlayerTemplate like the ContentUpdate method has.
Jira card: https://touchpointsoftware.atlassian.net/secure/RapidBoard.jspa?rapidView=6&projectKey=TPD&selectedIssue=TPD-892&assignee=5e9da7220d58350c2be09a8f …
=> TPD-910 - added thumbnail creation to Example Template

CmsWeb/Models/Api/AddContributionModel.cs
AddContribution API call can now accept a PeopleId parameter, which will match the contribution to a specific people record.
Also adds a related optional parameter to prevent new people from being created in the database if no match is found, by ignoring the contribution.
Tested against successfully on local build on the latest develop branch.
=> Enhance AddContribution API with new feature
